version: "2"
run:
  concurrency: 4
linters:
  enable:
    - copyloopvar
    - cyclop
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - makezero
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noctx
    - unconvert
    - unparam
    - wastedassign
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - goconst
          - wrapcheck
        path: (.*)test(.*).go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
