FROM golang:1.22 AS build

WORKDIR $GOPATH/src/app
COPY . .

RUN CGO_ENABLED=0 go build -o /redis-proxy ./cmd/redis-proxy/

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /redis-proxy /redis-proxy

ENTRYPOINT ["/redis-proxy"]
