FROM golang:latest AS build

WORKDIR $GOPATH/src/app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 go build -o /redis-proxy ./cmd/redis-proxy/

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /redis-proxy /redis-proxy

ENTRYPOINT ["/redis-proxy"]
