// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: admin_forward.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminForward_Forward_FullMethodName = "/AdminForward/Forward"
)

// AdminForwardClient is the client API for AdminForward service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminForward is the SigV4-bypass RPC the admin dashboard uses to
// reach the Raft leader from a follower. Design Section 3.3.
//
// The admin's HTTP layer authenticates the caller with a JWT cookie,
// resolves an access-key + role principal, and — if the local node
// is not the verified Raft leader — calls Forward over this RPC.
//
// The leader does NOT trust the inbound principal: it re-evaluates
// access-key membership and role against its own access-key
// configuration before dispatching to the adapter (Section 3.3.1
// "principal-aware internal RPC"). A follower whose configuration is
// mid-rolling-update can therefore not bypass the leader's view of
// authorisation.
//
// AdminForward is intentionally separate from the existing
// `Internal.Forward` RPC, which carries SigV4 traffic and has no
// principal field — sharing the same RPC would force the admin path
// to either smuggle a principal through reserved fields or strip
// the SigV4-only assumptions out of the existing Forward server.
type AdminForwardClient interface {
	// Forward dispatches an admin write operation on the leader's
	// behalf. Returns a structured response carrying the same JSON
	// payload the leader's handler would have written to the wire.
	Forward(ctx context.Context, in *AdminForwardRequest, opts ...grpc.CallOption) (*AdminForwardResponse, error)
}

type adminForwardClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminForwardClient(cc grpc.ClientConnInterface) AdminForwardClient {
	return &adminForwardClient{cc}
}

func (c *adminForwardClient) Forward(ctx context.Context, in *AdminForwardRequest, opts ...grpc.CallOption) (*AdminForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminForwardResponse)
	err := c.cc.Invoke(ctx, AdminForward_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminForwardServer is the server API for AdminForward service.
// All implementations must embed UnimplementedAdminForwardServer
// for forward compatibility.
//
// AdminForward is the SigV4-bypass RPC the admin dashboard uses to
// reach the Raft leader from a follower. Design Section 3.3.
//
// The admin's HTTP layer authenticates the caller with a JWT cookie,
// resolves an access-key + role principal, and — if the local node
// is not the verified Raft leader — calls Forward over this RPC.
//
// The leader does NOT trust the inbound principal: it re-evaluates
// access-key membership and role against its own access-key
// configuration before dispatching to the adapter (Section 3.3.1
// "principal-aware internal RPC"). A follower whose configuration is
// mid-rolling-update can therefore not bypass the leader's view of
// authorisation.
//
// AdminForward is intentionally separate from the existing
// `Internal.Forward` RPC, which carries SigV4 traffic and has no
// principal field — sharing the same RPC would force the admin path
// to either smuggle a principal through reserved fields or strip
// the SigV4-only assumptions out of the existing Forward server.
type AdminForwardServer interface {
	// Forward dispatches an admin write operation on the leader's
	// behalf. Returns a structured response carrying the same JSON
	// payload the leader's handler would have written to the wire.
	Forward(context.Context, *AdminForwardRequest) (*AdminForwardResponse, error)
	mustEmbedUnimplementedAdminForwardServer()
}

// UnimplementedAdminForwardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminForwardServer struct{}

func (UnimplementedAdminForwardServer) Forward(context.Context, *AdminForwardRequest) (*AdminForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedAdminForwardServer) mustEmbedUnimplementedAdminForwardServer() {}
func (UnimplementedAdminForwardServer) testEmbeddedByValue()                      {}

// UnsafeAdminForwardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminForwardServer will
// result in compilation errors.
type UnsafeAdminForwardServer interface {
	mustEmbedUnimplementedAdminForwardServer()
}

func RegisterAdminForwardServer(s grpc.ServiceRegistrar, srv AdminForwardServer) {
	// If the following call panics, it indicates UnimplementedAdminForwardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminForward_ServiceDesc, srv)
}

func _AdminForward_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminForwardServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminForward_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminForwardServer).Forward(ctx, req.(*AdminForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminForward_ServiceDesc is the grpc.ServiceDesc for AdminForward service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminForward_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AdminForward",
	HandlerType: (*AdminForwardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _AdminForward_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin_forward.proto",
}
