// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: admin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Admin_GetClusterOverview_FullMethodName    = "/Admin/GetClusterOverview"
	Admin_GetRaftGroups_FullMethodName         = "/Admin/GetRaftGroups"
	Admin_GetAdapterSummary_FullMethodName     = "/Admin/GetAdapterSummary"
	Admin_GetKeyVizMatrix_FullMethodName       = "/Admin/GetKeyVizMatrix"
	Admin_GetRouteDetail_FullMethodName        = "/Admin/GetRouteDetail"
	Admin_BeginBackup_FullMethodName           = "/Admin/BeginBackup"
	Admin_RenewBackup_FullMethodName           = "/Admin/RenewBackup"
	Admin_EndBackup_FullMethodName             = "/Admin/EndBackup"
	Admin_ListAdaptersAndScopes_FullMethodName = "/Admin/ListAdaptersAndScopes"
	Admin_StreamBackup_FullMethodName          = "/Admin/StreamBackup"
	Admin_GetNodeVersion_FullMethodName        = "/Admin/GetNodeVersion"
	Admin_StreamEvents_FullMethodName          = "/Admin/StreamEvents"
)

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Admin is the node-side admin gRPC service consumed by
// cmd/elastickv-admin. Every method requires "authorization: Bearer <token>"
// metadata unless the node was started with --adminInsecureNoAuth.
// See docs/admin_ui_key_visualizer_design.md §4 (Layer A).
type AdminClient interface {
	GetClusterOverview(ctx context.Context, in *GetClusterOverviewRequest, opts ...grpc.CallOption) (*GetClusterOverviewResponse, error)
	GetRaftGroups(ctx context.Context, in *GetRaftGroupsRequest, opts ...grpc.CallOption) (*GetRaftGroupsResponse, error)
	GetAdapterSummary(ctx context.Context, in *GetAdapterSummaryRequest, opts ...grpc.CallOption) (*GetAdapterSummaryResponse, error)
	GetKeyVizMatrix(ctx context.Context, in *GetKeyVizMatrixRequest, opts ...grpc.CallOption) (*GetKeyVizMatrixResponse, error)
	GetRouteDetail(ctx context.Context, in *GetRouteDetailRequest, opts ...grpc.CallOption) (*GetRouteDetailResponse, error)
	BeginBackup(ctx context.Context, in *BeginBackupRequest, opts ...grpc.CallOption) (*BeginBackupResponse, error)
	RenewBackup(ctx context.Context, in *RenewBackupRequest, opts ...grpc.CallOption) (*RenewBackupResponse, error)
	EndBackup(ctx context.Context, in *EndBackupRequest, opts ...grpc.CallOption) (*EndBackupResponse, error)
	ListAdaptersAndScopes(ctx context.Context, in *ListAdaptersAndScopesRequest, opts ...grpc.CallOption) (*ListAdaptersAndScopesResponse, error)
	StreamBackup(ctx context.Context, in *StreamBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupKV], error)
	GetNodeVersion(ctx context.Context, in *GetNodeVersionRequest, opts ...grpc.CallOption) (*GetNodeVersionResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsEvent], error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) GetClusterOverview(ctx context.Context, in *GetClusterOverviewRequest, opts ...grpc.CallOption) (*GetClusterOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterOverviewResponse)
	err := c.cc.Invoke(ctx, Admin_GetClusterOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetRaftGroups(ctx context.Context, in *GetRaftGroupsRequest, opts ...grpc.CallOption) (*GetRaftGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRaftGroupsResponse)
	err := c.cc.Invoke(ctx, Admin_GetRaftGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetAdapterSummary(ctx context.Context, in *GetAdapterSummaryRequest, opts ...grpc.CallOption) (*GetAdapterSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdapterSummaryResponse)
	err := c.cc.Invoke(ctx, Admin_GetAdapterSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetKeyVizMatrix(ctx context.Context, in *GetKeyVizMatrixRequest, opts ...grpc.CallOption) (*GetKeyVizMatrixResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyVizMatrixResponse)
	err := c.cc.Invoke(ctx, Admin_GetKeyVizMatrix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetRouteDetail(ctx context.Context, in *GetRouteDetailRequest, opts ...grpc.CallOption) (*GetRouteDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteDetailResponse)
	err := c.cc.Invoke(ctx, Admin_GetRouteDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) BeginBackup(ctx context.Context, in *BeginBackupRequest, opts ...grpc.CallOption) (*BeginBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginBackupResponse)
	err := c.cc.Invoke(ctx, Admin_BeginBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RenewBackup(ctx context.Context, in *RenewBackupRequest, opts ...grpc.CallOption) (*RenewBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewBackupResponse)
	err := c.cc.Invoke(ctx, Admin_RenewBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) EndBackup(ctx context.Context, in *EndBackupRequest, opts ...grpc.CallOption) (*EndBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EndBackupResponse)
	err := c.cc.Invoke(ctx, Admin_EndBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ListAdaptersAndScopes(ctx context.Context, in *ListAdaptersAndScopesRequest, opts ...grpc.CallOption) (*ListAdaptersAndScopesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdaptersAndScopesResponse)
	err := c.cc.Invoke(ctx, Admin_ListAdaptersAndScopes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) StreamBackup(ctx context.Context, in *StreamBackupRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupKV], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Admin_ServiceDesc.Streams[0], Admin_StreamBackup_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamBackupRequest, BackupKV]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Admin_StreamBackupClient = grpc.ServerStreamingClient[BackupKV]

func (c *adminClient) GetNodeVersion(ctx context.Context, in *GetNodeVersionRequest, opts ...grpc.CallOption) (*GetNodeVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeVersionResponse)
	err := c.cc.Invoke(ctx, Admin_GetNodeVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Admin_ServiceDesc.Streams[1], Admin_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Admin_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsEvent]

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility.
//
// Admin is the node-side admin gRPC service consumed by
// cmd/elastickv-admin. Every method requires "authorization: Bearer <token>"
// metadata unless the node was started with --adminInsecureNoAuth.
// See docs/admin_ui_key_visualizer_design.md §4 (Layer A).
type AdminServer interface {
	GetClusterOverview(context.Context, *GetClusterOverviewRequest) (*GetClusterOverviewResponse, error)
	GetRaftGroups(context.Context, *GetRaftGroupsRequest) (*GetRaftGroupsResponse, error)
	GetAdapterSummary(context.Context, *GetAdapterSummaryRequest) (*GetAdapterSummaryResponse, error)
	GetKeyVizMatrix(context.Context, *GetKeyVizMatrixRequest) (*GetKeyVizMatrixResponse, error)
	GetRouteDetail(context.Context, *GetRouteDetailRequest) (*GetRouteDetailResponse, error)
	BeginBackup(context.Context, *BeginBackupRequest) (*BeginBackupResponse, error)
	RenewBackup(context.Context, *RenewBackupRequest) (*RenewBackupResponse, error)
	EndBackup(context.Context, *EndBackupRequest) (*EndBackupResponse, error)
	ListAdaptersAndScopes(context.Context, *ListAdaptersAndScopesRequest) (*ListAdaptersAndScopesResponse, error)
	StreamBackup(*StreamBackupRequest, grpc.ServerStreamingServer[BackupKV]) error
	GetNodeVersion(context.Context, *GetNodeVersionRequest) (*GetNodeVersionResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsEvent]) error
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServer struct{}

func (UnimplementedAdminServer) GetClusterOverview(context.Context, *GetClusterOverviewRequest) (*GetClusterOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterOverview not implemented")
}
func (UnimplementedAdminServer) GetRaftGroups(context.Context, *GetRaftGroupsRequest) (*GetRaftGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRaftGroups not implemented")
}
func (UnimplementedAdminServer) GetAdapterSummary(context.Context, *GetAdapterSummaryRequest) (*GetAdapterSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdapterSummary not implemented")
}
func (UnimplementedAdminServer) GetKeyVizMatrix(context.Context, *GetKeyVizMatrixRequest) (*GetKeyVizMatrixResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyVizMatrix not implemented")
}
func (UnimplementedAdminServer) GetRouteDetail(context.Context, *GetRouteDetailRequest) (*GetRouteDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteDetail not implemented")
}
func (UnimplementedAdminServer) BeginBackup(context.Context, *BeginBackupRequest) (*BeginBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginBackup not implemented")
}
func (UnimplementedAdminServer) RenewBackup(context.Context, *RenewBackupRequest) (*RenewBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewBackup not implemented")
}
func (UnimplementedAdminServer) EndBackup(context.Context, *EndBackupRequest) (*EndBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EndBackup not implemented")
}
func (UnimplementedAdminServer) ListAdaptersAndScopes(context.Context, *ListAdaptersAndScopesRequest) (*ListAdaptersAndScopesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdaptersAndScopes not implemented")
}
func (UnimplementedAdminServer) StreamBackup(*StreamBackupRequest, grpc.ServerStreamingServer[BackupKV]) error {
	return status.Error(codes.Unimplemented, "method StreamBackup not implemented")
}
func (UnimplementedAdminServer) GetNodeVersion(context.Context, *GetNodeVersionRequest) (*GetNodeVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeVersion not implemented")
}
func (UnimplementedAdminServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsEvent]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}
func (UnimplementedAdminServer) testEmbeddedByValue()               {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	// If the following call panics, it indicates UnimplementedAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_GetClusterOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetClusterOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetClusterOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetClusterOverview(ctx, req.(*GetClusterOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetRaftGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRaftGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetRaftGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetRaftGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetRaftGroups(ctx, req.(*GetRaftGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetAdapterSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdapterSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetAdapterSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetAdapterSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetAdapterSummary(ctx, req.(*GetAdapterSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetKeyVizMatrix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyVizMatrixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetKeyVizMatrix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetKeyVizMatrix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetKeyVizMatrix(ctx, req.(*GetKeyVizMatrixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetRouteDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetRouteDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetRouteDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetRouteDetail(ctx, req.(*GetRouteDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_BeginBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).BeginBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_BeginBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).BeginBackup(ctx, req.(*BeginBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RenewBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RenewBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_RenewBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RenewBackup(ctx, req.(*RenewBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_EndBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).EndBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_EndBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).EndBackup(ctx, req.(*EndBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ListAdaptersAndScopes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdaptersAndScopesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ListAdaptersAndScopes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_ListAdaptersAndScopes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ListAdaptersAndScopes(ctx, req.(*ListAdaptersAndScopesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_StreamBackup_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamBackupRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServer).StreamBackup(m, &grpc.GenericServerStream[StreamBackupRequest, BackupKV]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Admin_StreamBackupServer = grpc.ServerStreamingServer[BackupKV]

func _Admin_GetNodeVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetNodeVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Admin_GetNodeVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetNodeVersion(ctx, req.(*GetNodeVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AdminServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Admin_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsEvent]

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterOverview",
			Handler:    _Admin_GetClusterOverview_Handler,
		},
		{
			MethodName: "GetRaftGroups",
			Handler:    _Admin_GetRaftGroups_Handler,
		},
		{
			MethodName: "GetAdapterSummary",
			Handler:    _Admin_GetAdapterSummary_Handler,
		},
		{
			MethodName: "GetKeyVizMatrix",
			Handler:    _Admin_GetKeyVizMatrix_Handler,
		},
		{
			MethodName: "GetRouteDetail",
			Handler:    _Admin_GetRouteDetail_Handler,
		},
		{
			MethodName: "BeginBackup",
			Handler:    _Admin_BeginBackup_Handler,
		},
		{
			MethodName: "RenewBackup",
			Handler:    _Admin_RenewBackup_Handler,
		},
		{
			MethodName: "EndBackup",
			Handler:    _Admin_EndBackup_Handler,
		},
		{
			MethodName: "ListAdaptersAndScopes",
			Handler:    _Admin_ListAdaptersAndScopes_Handler,
		},
		{
			MethodName: "GetNodeVersion",
			Handler:    _Admin_GetNodeVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBackup",
			Handler:       _Admin_StreamBackup_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _Admin_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "admin.proto",
}
