// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: distribution.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteState int32

const (
	RouteState_ROUTE_STATE_UNSPECIFIED      RouteState = 0
	RouteState_ROUTE_STATE_ACTIVE           RouteState = 1
	RouteState_ROUTE_STATE_WRITE_FENCED     RouteState = 2
	RouteState_ROUTE_STATE_MIGRATING_SOURCE RouteState = 3
	RouteState_ROUTE_STATE_MIGRATING_TARGET RouteState = 4
)

// Enum value maps for RouteState.
var (
	RouteState_name = map[int32]string{
		0: "ROUTE_STATE_UNSPECIFIED",
		1: "ROUTE_STATE_ACTIVE",
		2: "ROUTE_STATE_WRITE_FENCED",
		3: "ROUTE_STATE_MIGRATING_SOURCE",
		4: "ROUTE_STATE_MIGRATING_TARGET",
	}
	RouteState_value = map[string]int32{
		"ROUTE_STATE_UNSPECIFIED":      0,
		"ROUTE_STATE_ACTIVE":           1,
		"ROUTE_STATE_WRITE_FENCED":     2,
		"ROUTE_STATE_MIGRATING_SOURCE": 3,
		"ROUTE_STATE_MIGRATING_TARGET": 4,
	}
)

func (x RouteState) Enum() *RouteState {
	p := new(RouteState)
	*p = x
	return p
}

func (x RouteState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteState) Descriptor() protoreflect.EnumDescriptor {
	return file_distribution_proto_enumTypes[0].Descriptor()
}

func (RouteState) Type() protoreflect.EnumType {
	return &file_distribution_proto_enumTypes[0]
}

func (x RouteState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteState.Descriptor instead.
func (RouteState) EnumDescriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{0}
}

type SplitJobPhase int32

const (
	SplitJobPhase_SPLIT_JOB_PHASE_NONE       SplitJobPhase = 0
	SplitJobPhase_SPLIT_JOB_PHASE_PLANNED    SplitJobPhase = 1
	SplitJobPhase_SPLIT_JOB_PHASE_BACKFILL   SplitJobPhase = 2
	SplitJobPhase_SPLIT_JOB_PHASE_FENCE      SplitJobPhase = 3
	SplitJobPhase_SPLIT_JOB_PHASE_DELTA_COPY SplitJobPhase = 4
	SplitJobPhase_SPLIT_JOB_PHASE_CUTOVER    SplitJobPhase = 5
	SplitJobPhase_SPLIT_JOB_PHASE_CLEANUP    SplitJobPhase = 6
	SplitJobPhase_SPLIT_JOB_PHASE_DONE       SplitJobPhase = 7
	SplitJobPhase_SPLIT_JOB_PHASE_FAILED     SplitJobPhase = 8
	SplitJobPhase_SPLIT_JOB_PHASE_ABANDONING SplitJobPhase = 9
	SplitJobPhase_SPLIT_JOB_PHASE_ABANDONED  SplitJobPhase = 10
)

// Enum value maps for SplitJobPhase.
var (
	SplitJobPhase_name = map[int32]string{
		0:  "SPLIT_JOB_PHASE_NONE",
		1:  "SPLIT_JOB_PHASE_PLANNED",
		2:  "SPLIT_JOB_PHASE_BACKFILL",
		3:  "SPLIT_JOB_PHASE_FENCE",
		4:  "SPLIT_JOB_PHASE_DELTA_COPY",
		5:  "SPLIT_JOB_PHASE_CUTOVER",
		6:  "SPLIT_JOB_PHASE_CLEANUP",
		7:  "SPLIT_JOB_PHASE_DONE",
		8:  "SPLIT_JOB_PHASE_FAILED",
		9:  "SPLIT_JOB_PHASE_ABANDONING",
		10: "SPLIT_JOB_PHASE_ABANDONED",
	}
	SplitJobPhase_value = map[string]int32{
		"SPLIT_JOB_PHASE_NONE":       0,
		"SPLIT_JOB_PHASE_PLANNED":    1,
		"SPLIT_JOB_PHASE_BACKFILL":   2,
		"SPLIT_JOB_PHASE_FENCE":      3,
		"SPLIT_JOB_PHASE_DELTA_COPY": 4,
		"SPLIT_JOB_PHASE_CUTOVER":    5,
		"SPLIT_JOB_PHASE_CLEANUP":    6,
		"SPLIT_JOB_PHASE_DONE":       7,
		"SPLIT_JOB_PHASE_FAILED":     8,
		"SPLIT_JOB_PHASE_ABANDONING": 9,
		"SPLIT_JOB_PHASE_ABANDONED":  10,
	}
)

func (x SplitJobPhase) Enum() *SplitJobPhase {
	p := new(SplitJobPhase)
	*p = x
	return p
}

func (x SplitJobPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitJobPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_distribution_proto_enumTypes[1].Descriptor()
}

func (SplitJobPhase) Type() protoreflect.EnumType {
	return &file_distribution_proto_enumTypes[1]
}

func (x SplitJobPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitJobPhase.Descriptor instead.
func (SplitJobPhase) EnumDescriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{1}
}

type SplitJobBarrierState int32

const (
	SplitJobBarrierState_SPLIT_JOB_BARRIER_STATE_NONE     SplitJobBarrierState = 0
	SplitJobBarrierState_SPLIT_JOB_BARRIER_STATE_ARMING   SplitJobBarrierState = 1
	SplitJobBarrierState_SPLIT_JOB_BARRIER_STATE_ARMED    SplitJobBarrierState = 2
	SplitJobBarrierState_SPLIT_JOB_BARRIER_STATE_CLEARING SplitJobBarrierState = 3
)

// Enum value maps for SplitJobBarrierState.
var (
	SplitJobBarrierState_name = map[int32]string{
		0: "SPLIT_JOB_BARRIER_STATE_NONE",
		1: "SPLIT_JOB_BARRIER_STATE_ARMING",
		2: "SPLIT_JOB_BARRIER_STATE_ARMED",
		3: "SPLIT_JOB_BARRIER_STATE_CLEARING",
	}
	SplitJobBarrierState_value = map[string]int32{
		"SPLIT_JOB_BARRIER_STATE_NONE":     0,
		"SPLIT_JOB_BARRIER_STATE_ARMING":   1,
		"SPLIT_JOB_BARRIER_STATE_ARMED":    2,
		"SPLIT_JOB_BARRIER_STATE_CLEARING": 3,
	}
)

func (x SplitJobBarrierState) Enum() *SplitJobBarrierState {
	p := new(SplitJobBarrierState)
	*p = x
	return p
}

func (x SplitJobBarrierState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitJobBarrierState) Descriptor() protoreflect.EnumDescriptor {
	return file_distribution_proto_enumTypes[2].Descriptor()
}

func (SplitJobBarrierState) Type() protoreflect.EnumType {
	return &file_distribution_proto_enumTypes[2]
}

func (x SplitJobBarrierState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitJobBarrierState.Descriptor instead.
func (SplitJobBarrierState) EnumDescriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{2}
}

type SplitJobExportPhase int32

const (
	SplitJobExportPhase_SPLIT_JOB_EXPORT_PHASE_NONE       SplitJobExportPhase = 0
	SplitJobExportPhase_SPLIT_JOB_EXPORT_PHASE_BACKFILL   SplitJobExportPhase = 1
	SplitJobExportPhase_SPLIT_JOB_EXPORT_PHASE_DELTA_COPY SplitJobExportPhase = 2
)

// Enum value maps for SplitJobExportPhase.
var (
	SplitJobExportPhase_name = map[int32]string{
		0: "SPLIT_JOB_EXPORT_PHASE_NONE",
		1: "SPLIT_JOB_EXPORT_PHASE_BACKFILL",
		2: "SPLIT_JOB_EXPORT_PHASE_DELTA_COPY",
	}
	SplitJobExportPhase_value = map[string]int32{
		"SPLIT_JOB_EXPORT_PHASE_NONE":       0,
		"SPLIT_JOB_EXPORT_PHASE_BACKFILL":   1,
		"SPLIT_JOB_EXPORT_PHASE_DELTA_COPY": 2,
	}
)

func (x SplitJobExportPhase) Enum() *SplitJobExportPhase {
	p := new(SplitJobExportPhase)
	*p = x
	return p
}

func (x SplitJobExportPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitJobExportPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_distribution_proto_enumTypes[3].Descriptor()
}

func (SplitJobExportPhase) Type() protoreflect.EnumType {
	return &file_distribution_proto_enumTypes[3]
}

func (x SplitJobExportPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitJobExportPhase.Descriptor instead.
func (SplitJobExportPhase) EnumDescriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{3}
}

type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_distribution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{0}
}

func (x *GetRouteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start is inclusive and end is exclusive. A missing end denotes an
	// unbounded range extending to positive infinity.
	Start         []byte `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           []byte `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	RaftGroupId   uint64 `protobuf:"varint,3,opt,name=raft_group_id,json=raftGroupId,proto3" json:"raft_group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_distribution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{1}
}

func (x *GetRouteResponse) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetRouteResponse) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetRouteResponse) GetRaftGroupId() uint64 {
	if x != nil {
		return x.RaftGroupId
	}
	return 0
}

type GetTimestampRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimestampRequest) Reset() {
	*x = GetTimestampRequest{}
	mi := &file_distribution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampRequest) ProtoMessage() {}

func (x *GetTimestampRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampRequest.ProtoReflect.Descriptor instead.
func (*GetTimestampRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{2}
}

type GetTimestampResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimestampResponse) Reset() {
	*x = GetTimestampResponse{}
	mi := &file_distribution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimestampResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimestampResponse) ProtoMessage() {}

func (x *GetTimestampResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimestampResponse.ProtoReflect.Descriptor instead.
func (*GetTimestampResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimestampResponse) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type RouteDescriptor struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RouteId                uint64                 `protobuf:"varint,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Start                  []byte                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End                    []byte                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	RaftGroupId            uint64                 `protobuf:"varint,4,opt,name=raft_group_id,json=raftGroupId,proto3" json:"raft_group_id,omitempty"`
	State                  RouteState             `protobuf:"varint,5,opt,name=state,proto3,enum=RouteState" json:"state,omitempty"`
	ParentRouteId          uint64                 `protobuf:"varint,6,opt,name=parent_route_id,json=parentRouteId,proto3" json:"parent_route_id,omitempty"`
	SplitAtHlc             uint64                 `protobuf:"varint,7,opt,name=split_at_hlc,json=splitAtHlc,proto3" json:"split_at_hlc,omitempty"`
	StagedVisibilityActive bool                   `protobuf:"varint,8,opt,name=staged_visibility_active,json=stagedVisibilityActive,proto3" json:"staged_visibility_active,omitempty"`
	MigrationJobId         uint64                 `protobuf:"varint,9,opt,name=migration_job_id,json=migrationJobId,proto3" json:"migration_job_id,omitempty"`
	MinWriteTsExclusive    uint64                 `protobuf:"varint,10,opt,name=min_write_ts_exclusive,json=minWriteTsExclusive,proto3" json:"min_write_ts_exclusive,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RouteDescriptor) Reset() {
	*x = RouteDescriptor{}
	mi := &file_distribution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDescriptor) ProtoMessage() {}

func (x *RouteDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDescriptor.ProtoReflect.Descriptor instead.
func (*RouteDescriptor) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{4}
}

func (x *RouteDescriptor) GetRouteId() uint64 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *RouteDescriptor) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RouteDescriptor) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *RouteDescriptor) GetRaftGroupId() uint64 {
	if x != nil {
		return x.RaftGroupId
	}
	return 0
}

func (x *RouteDescriptor) GetState() RouteState {
	if x != nil {
		return x.State
	}
	return RouteState_ROUTE_STATE_UNSPECIFIED
}

func (x *RouteDescriptor) GetParentRouteId() uint64 {
	if x != nil {
		return x.ParentRouteId
	}
	return 0
}

func (x *RouteDescriptor) GetSplitAtHlc() uint64 {
	if x != nil {
		return x.SplitAtHlc
	}
	return 0
}

func (x *RouteDescriptor) GetStagedVisibilityActive() bool {
	if x != nil {
		return x.StagedVisibilityActive
	}
	return false
}

func (x *RouteDescriptor) GetMigrationJobId() uint64 {
	if x != nil {
		return x.MigrationJobId
	}
	return 0
}

func (x *RouteDescriptor) GetMinWriteTsExclusive() uint64 {
	if x != nil {
		return x.MinWriteTsExclusive
	}
	return 0
}

type SplitJobBracketProgress struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BracketId         uint64                 `protobuf:"varint,1,opt,name=bracket_id,json=bracketId,proto3" json:"bracket_id,omitempty"`
	Family            uint32                 `protobuf:"varint,2,opt,name=family,proto3" json:"family,omitempty"`
	ExportPhase       SplitJobExportPhase    `protobuf:"varint,3,opt,name=export_phase,json=exportPhase,proto3,enum=SplitJobExportPhase" json:"export_phase,omitempty"`
	Cursor            []byte                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Done              bool                   `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	ScannedBytes      uint64                 `protobuf:"varint,6,opt,name=scanned_bytes,json=scannedBytes,proto3" json:"scanned_bytes,omitempty"`
	AcceptedRows      uint64                 `protobuf:"varint,7,opt,name=accepted_rows,json=acceptedRows,proto3" json:"accepted_rows,omitempty"`
	LastAckedBatchSeq uint64                 `protobuf:"varint,8,opt,name=last_acked_batch_seq,json=lastAckedBatchSeq,proto3" json:"last_acked_batch_seq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SplitJobBracketProgress) Reset() {
	*x = SplitJobBracketProgress{}
	mi := &file_distribution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitJobBracketProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitJobBracketProgress) ProtoMessage() {}

func (x *SplitJobBracketProgress) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitJobBracketProgress.ProtoReflect.Descriptor instead.
func (*SplitJobBracketProgress) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{5}
}

func (x *SplitJobBracketProgress) GetBracketId() uint64 {
	if x != nil {
		return x.BracketId
	}
	return 0
}

func (x *SplitJobBracketProgress) GetFamily() uint32 {
	if x != nil {
		return x.Family
	}
	return 0
}

func (x *SplitJobBracketProgress) GetExportPhase() SplitJobExportPhase {
	if x != nil {
		return x.ExportPhase
	}
	return SplitJobExportPhase_SPLIT_JOB_EXPORT_PHASE_NONE
}

func (x *SplitJobBracketProgress) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *SplitJobBracketProgress) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *SplitJobBracketProgress) GetScannedBytes() uint64 {
	if x != nil {
		return x.ScannedBytes
	}
	return 0
}

func (x *SplitJobBracketProgress) GetAcceptedRows() uint64 {
	if x != nil {
		return x.AcceptedRows
	}
	return 0
}

func (x *SplitJobBracketProgress) GetLastAckedBatchSeq() uint64 {
	if x != nil {
		return x.LastAckedBatchSeq
	}
	return 0
}

type SplitJob struct {
	state                            protoimpl.MessageState     `protogen:"open.v1"`
	JobId                            uint64                     `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	SourceRouteId                    uint64                     `protobuf:"varint,2,opt,name=source_route_id,json=sourceRouteId,proto3" json:"source_route_id,omitempty"`
	SplitKey                         []byte                     `protobuf:"bytes,3,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	TargetGroupId                    uint64                     `protobuf:"varint,4,opt,name=target_group_id,json=targetGroupId,proto3" json:"target_group_id,omitempty"`
	Phase                            SplitJobPhase              `protobuf:"varint,5,opt,name=phase,proto3,enum=SplitJobPhase" json:"phase,omitempty"`
	RetryPhase                       SplitJobPhase              `protobuf:"varint,6,opt,name=retry_phase,json=retryPhase,proto3,enum=SplitJobPhase" json:"retry_phase,omitempty"`
	AbandonFromPhase                 SplitJobPhase              `protobuf:"varint,7,opt,name=abandon_from_phase,json=abandonFromPhase,proto3,enum=SplitJobPhase" json:"abandon_from_phase,omitempty"`
	SnapshotTs                       uint64                     `protobuf:"varint,8,opt,name=snapshot_ts,json=snapshotTs,proto3" json:"snapshot_ts,omitempty"`
	SnapshotMinAdmittedTs            uint64                     `protobuf:"varint,9,opt,name=snapshot_min_admitted_ts,json=snapshotMinAdmittedTs,proto3" json:"snapshot_min_admitted_ts,omitempty"`
	WriteTrackerArmed                bool                       `protobuf:"varint,10,opt,name=write_tracker_armed,json=writeTrackerArmed,proto3" json:"write_tracker_armed,omitempty"`
	DeltaFloor                       uint64                     `protobuf:"varint,11,opt,name=delta_floor,json=deltaFloor,proto3" json:"delta_floor,omitempty"`
	PostFenceDrainCompleted          bool                       `protobuf:"varint,12,opt,name=post_fence_drain_completed,json=postFenceDrainCompleted,proto3" json:"post_fence_drain_completed,omitempty"`
	FenceTs                          uint64                     `protobuf:"varint,13,opt,name=fence_ts,json=fenceTs,proto3" json:"fence_ts,omitempty"`
	CutoverVersion                   uint64                     `protobuf:"varint,14,opt,name=cutover_version,json=cutoverVersion,proto3" json:"cutover_version,omitempty"`
	CutoverReadFenceState            SplitJobBarrierState       `protobuf:"varint,15,opt,name=cutover_read_fence_state,json=cutoverReadFenceState,proto3,enum=SplitJobBarrierState" json:"cutover_read_fence_state,omitempty"`
	TargetStagedReadinessState       SplitJobBarrierState       `protobuf:"varint,16,opt,name=target_staged_readiness_state,json=targetStagedReadinessState,proto3,enum=SplitJobBarrierState" json:"target_staged_readiness_state,omitempty"`
	SourceCutoverReadFenceAckCursor  []byte                     `protobuf:"bytes,17,opt,name=source_cutover_read_fence_ack_cursor,json=sourceCutoverReadFenceAckCursor,proto3" json:"source_cutover_read_fence_ack_cursor,omitempty"`
	TargetStagedReadinessAckCursor   []byte                     `protobuf:"bytes,18,opt,name=target_staged_readiness_ack_cursor,json=targetStagedReadinessAckCursor,proto3" json:"target_staged_readiness_ack_cursor,omitempty"`
	Cursor                           []byte                     `protobuf:"bytes,19,opt,name=cursor,proto3" json:"cursor,omitempty"`
	MaxImportedTs                    uint64                     `protobuf:"varint,20,opt,name=max_imported_ts,json=maxImportedTs,proto3" json:"max_imported_ts,omitempty"`
	TargetPromotionDone              bool                       `protobuf:"varint,21,opt,name=target_promotion_done,json=targetPromotionDone,proto3" json:"target_promotion_done,omitempty"`
	PromotionCompletedTs             uint64                     `protobuf:"varint,22,opt,name=promotion_completed_ts,json=promotionCompletedTs,proto3" json:"promotion_completed_ts,omitempty"`
	FenceCatalogVersion              uint64                     `protobuf:"varint,23,opt,name=fence_catalog_version,json=fenceCatalogVersion,proto3" json:"fence_catalog_version,omitempty"`
	FenceAckCursor                   []byte                     `protobuf:"bytes,24,opt,name=fence_ack_cursor,json=fenceAckCursor,proto3" json:"fence_ack_cursor,omitempty"`
	SourceCutoverAckCursor           []byte                     `protobuf:"bytes,25,opt,name=source_cutover_ack_cursor,json=sourceCutoverAckCursor,proto3" json:"source_cutover_ack_cursor,omitempty"`
	SourceReadDrainCursor            []byte                     `protobuf:"bytes,26,opt,name=source_read_drain_cursor,json=sourceReadDrainCursor,proto3" json:"source_read_drain_cursor,omitempty"`
	TargetClearedDescriptorAckCursor []byte                     `protobuf:"bytes,27,opt,name=target_cleared_descriptor_ack_cursor,json=targetClearedDescriptorAckCursor,proto3" json:"target_cleared_descriptor_ack_cursor,omitempty"`
	BracketProgress                  []*SplitJobBracketProgress `protobuf:"bytes,28,rep,name=bracket_progress,json=bracketProgress,proto3" json:"bracket_progress,omitempty"`
	SourceRetentionPinTs             uint64                     `protobuf:"varint,29,opt,name=source_retention_pin_ts,json=sourceRetentionPinTs,proto3" json:"source_retention_pin_ts,omitempty"`
	LastError                        string                     `protobuf:"bytes,30,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	StartedAtMs                      int64                      `protobuf:"varint,31,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	UpdatedAtMs                      int64                      `protobuf:"varint,32,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	TerminalAtMs                     int64                      `protobuf:"varint,33,opt,name=terminal_at_ms,json=terminalAtMs,proto3" json:"terminal_at_ms,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *SplitJob) Reset() {
	*x = SplitJob{}
	mi := &file_distribution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitJob) ProtoMessage() {}

func (x *SplitJob) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitJob.ProtoReflect.Descriptor instead.
func (*SplitJob) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{6}
}

func (x *SplitJob) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *SplitJob) GetSourceRouteId() uint64 {
	if x != nil {
		return x.SourceRouteId
	}
	return 0
}

func (x *SplitJob) GetSplitKey() []byte {
	if x != nil {
		return x.SplitKey
	}
	return nil
}

func (x *SplitJob) GetTargetGroupId() uint64 {
	if x != nil {
		return x.TargetGroupId
	}
	return 0
}

func (x *SplitJob) GetPhase() SplitJobPhase {
	if x != nil {
		return x.Phase
	}
	return SplitJobPhase_SPLIT_JOB_PHASE_NONE
}

func (x *SplitJob) GetRetryPhase() SplitJobPhase {
	if x != nil {
		return x.RetryPhase
	}
	return SplitJobPhase_SPLIT_JOB_PHASE_NONE
}

func (x *SplitJob) GetAbandonFromPhase() SplitJobPhase {
	if x != nil {
		return x.AbandonFromPhase
	}
	return SplitJobPhase_SPLIT_JOB_PHASE_NONE
}

func (x *SplitJob) GetSnapshotTs() uint64 {
	if x != nil {
		return x.SnapshotTs
	}
	return 0
}

func (x *SplitJob) GetSnapshotMinAdmittedTs() uint64 {
	if x != nil {
		return x.SnapshotMinAdmittedTs
	}
	return 0
}

func (x *SplitJob) GetWriteTrackerArmed() bool {
	if x != nil {
		return x.WriteTrackerArmed
	}
	return false
}

func (x *SplitJob) GetDeltaFloor() uint64 {
	if x != nil {
		return x.DeltaFloor
	}
	return 0
}

func (x *SplitJob) GetPostFenceDrainCompleted() bool {
	if x != nil {
		return x.PostFenceDrainCompleted
	}
	return false
}

func (x *SplitJob) GetFenceTs() uint64 {
	if x != nil {
		return x.FenceTs
	}
	return 0
}

func (x *SplitJob) GetCutoverVersion() uint64 {
	if x != nil {
		return x.CutoverVersion
	}
	return 0
}

func (x *SplitJob) GetCutoverReadFenceState() SplitJobBarrierState {
	if x != nil {
		return x.CutoverReadFenceState
	}
	return SplitJobBarrierState_SPLIT_JOB_BARRIER_STATE_NONE
}

func (x *SplitJob) GetTargetStagedReadinessState() SplitJobBarrierState {
	if x != nil {
		return x.TargetStagedReadinessState
	}
	return SplitJobBarrierState_SPLIT_JOB_BARRIER_STATE_NONE
}

func (x *SplitJob) GetSourceCutoverReadFenceAckCursor() []byte {
	if x != nil {
		return x.SourceCutoverReadFenceAckCursor
	}
	return nil
}

func (x *SplitJob) GetTargetStagedReadinessAckCursor() []byte {
	if x != nil {
		return x.TargetStagedReadinessAckCursor
	}
	return nil
}

func (x *SplitJob) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *SplitJob) GetMaxImportedTs() uint64 {
	if x != nil {
		return x.MaxImportedTs
	}
	return 0
}

func (x *SplitJob) GetTargetPromotionDone() bool {
	if x != nil {
		return x.TargetPromotionDone
	}
	return false
}

func (x *SplitJob) GetPromotionCompletedTs() uint64 {
	if x != nil {
		return x.PromotionCompletedTs
	}
	return 0
}

func (x *SplitJob) GetFenceCatalogVersion() uint64 {
	if x != nil {
		return x.FenceCatalogVersion
	}
	return 0
}

func (x *SplitJob) GetFenceAckCursor() []byte {
	if x != nil {
		return x.FenceAckCursor
	}
	return nil
}

func (x *SplitJob) GetSourceCutoverAckCursor() []byte {
	if x != nil {
		return x.SourceCutoverAckCursor
	}
	return nil
}

func (x *SplitJob) GetSourceReadDrainCursor() []byte {
	if x != nil {
		return x.SourceReadDrainCursor
	}
	return nil
}

func (x *SplitJob) GetTargetClearedDescriptorAckCursor() []byte {
	if x != nil {
		return x.TargetClearedDescriptorAckCursor
	}
	return nil
}

func (x *SplitJob) GetBracketProgress() []*SplitJobBracketProgress {
	if x != nil {
		return x.BracketProgress
	}
	return nil
}

func (x *SplitJob) GetSourceRetentionPinTs() uint64 {
	if x != nil {
		return x.SourceRetentionPinTs
	}
	return 0
}

func (x *SplitJob) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *SplitJob) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *SplitJob) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *SplitJob) GetTerminalAtMs() int64 {
	if x != nil {
		return x.TerminalAtMs
	}
	return 0
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_distribution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{7}
}

type ListRoutesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CatalogVersion uint64                 `protobuf:"varint,1,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	Routes         []*RouteDescriptor     `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_distribution_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{8}
}

func (x *ListRoutesResponse) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

func (x *ListRoutesResponse) GetRoutes() []*RouteDescriptor {
	if x != nil {
		return x.Routes
	}
	return nil
}

type SplitRangeRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExpectedCatalogVersion uint64                 `protobuf:"varint,1,opt,name=expected_catalog_version,json=expectedCatalogVersion,proto3" json:"expected_catalog_version,omitempty"`
	RouteId                uint64                 `protobuf:"varint,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	SplitKey               []byte                 `protobuf:"bytes,3,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SplitRangeRequest) Reset() {
	*x = SplitRangeRequest{}
	mi := &file_distribution_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRangeRequest) ProtoMessage() {}

func (x *SplitRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRangeRequest.ProtoReflect.Descriptor instead.
func (*SplitRangeRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{9}
}

func (x *SplitRangeRequest) GetExpectedCatalogVersion() uint64 {
	if x != nil {
		return x.ExpectedCatalogVersion
	}
	return 0
}

func (x *SplitRangeRequest) GetRouteId() uint64 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *SplitRangeRequest) GetSplitKey() []byte {
	if x != nil {
		return x.SplitKey
	}
	return nil
}

type SplitRangeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CatalogVersion uint64                 `protobuf:"varint,1,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	Left           *RouteDescriptor       `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right          *RouteDescriptor       `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SplitRangeResponse) Reset() {
	*x = SplitRangeResponse{}
	mi := &file_distribution_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitRangeResponse) ProtoMessage() {}

func (x *SplitRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitRangeResponse.ProtoReflect.Descriptor instead.
func (*SplitRangeResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{10}
}

func (x *SplitRangeResponse) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

func (x *SplitRangeResponse) GetLeft() *RouteDescriptor {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *SplitRangeResponse) GetRight() *RouteDescriptor {
	if x != nil {
		return x.Right
	}
	return nil
}

type StartSplitMigrationRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ExpectedCatalogVersion uint64                 `protobuf:"varint,1,opt,name=expected_catalog_version,json=expectedCatalogVersion,proto3" json:"expected_catalog_version,omitempty"`
	RouteId                uint64                 `protobuf:"varint,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	SplitKey               []byte                 `protobuf:"bytes,3,opt,name=split_key,json=splitKey,proto3" json:"split_key,omitempty"`
	TargetGroupId          uint64                 `protobuf:"varint,4,opt,name=target_group_id,json=targetGroupId,proto3" json:"target_group_id,omitempty"`
	Options                map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartSplitMigrationRequest) Reset() {
	*x = StartSplitMigrationRequest{}
	mi := &file_distribution_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSplitMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSplitMigrationRequest) ProtoMessage() {}

func (x *StartSplitMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSplitMigrationRequest.ProtoReflect.Descriptor instead.
func (*StartSplitMigrationRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{11}
}

func (x *StartSplitMigrationRequest) GetExpectedCatalogVersion() uint64 {
	if x != nil {
		return x.ExpectedCatalogVersion
	}
	return 0
}

func (x *StartSplitMigrationRequest) GetRouteId() uint64 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *StartSplitMigrationRequest) GetSplitKey() []byte {
	if x != nil {
		return x.SplitKey
	}
	return nil
}

func (x *StartSplitMigrationRequest) GetTargetGroupId() uint64 {
	if x != nil {
		return x.TargetGroupId
	}
	return 0
}

func (x *StartSplitMigrationRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type StartSplitMigrationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CatalogVersion uint64                 `protobuf:"varint,1,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	JobId          uint64                 `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartSplitMigrationResponse) Reset() {
	*x = StartSplitMigrationResponse{}
	mi := &file_distribution_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSplitMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSplitMigrationResponse) ProtoMessage() {}

func (x *StartSplitMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSplitMigrationResponse.ProtoReflect.Descriptor instead.
func (*StartSplitMigrationResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{12}
}

func (x *StartSplitMigrationResponse) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

func (x *StartSplitMigrationResponse) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetRouteOwnershipRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CatalogVersion uint64                 `protobuf:"varint,2,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRouteOwnershipRequest) Reset() {
	*x = GetRouteOwnershipRequest{}
	mi := &file_distribution_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteOwnershipRequest) ProtoMessage() {}

func (x *GetRouteOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteOwnershipRequest.ProtoReflect.Descriptor instead.
func (*GetRouteOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{13}
}

func (x *GetRouteOwnershipRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRouteOwnershipRequest) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

type GetRouteOwnershipResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Route          *RouteDescriptor       `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	CatalogVersion uint64                 `protobuf:"varint,2,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	Found          bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRouteOwnershipResponse) Reset() {
	*x = GetRouteOwnershipResponse{}
	mi := &file_distribution_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteOwnershipResponse) ProtoMessage() {}

func (x *GetRouteOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteOwnershipResponse.ProtoReflect.Descriptor instead.
func (*GetRouteOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{14}
}

func (x *GetRouteOwnershipResponse) GetRoute() *RouteDescriptor {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *GetRouteOwnershipResponse) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

func (x *GetRouteOwnershipResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetIntersectingRoutesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Start          []byte                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End            []byte                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	CatalogVersion uint64                 `protobuf:"varint,3,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIntersectingRoutesRequest) Reset() {
	*x = GetIntersectingRoutesRequest{}
	mi := &file_distribution_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntersectingRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntersectingRoutesRequest) ProtoMessage() {}

func (x *GetIntersectingRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntersectingRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetIntersectingRoutesRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{15}
}

func (x *GetIntersectingRoutesRequest) GetStart() []byte {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *GetIntersectingRoutesRequest) GetEnd() []byte {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *GetIntersectingRoutesRequest) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

type GetIntersectingRoutesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Routes         []*RouteDescriptor     `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	CatalogVersion uint64                 `protobuf:"varint,2,opt,name=catalog_version,json=catalogVersion,proto3" json:"catalog_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIntersectingRoutesResponse) Reset() {
	*x = GetIntersectingRoutesResponse{}
	mi := &file_distribution_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntersectingRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntersectingRoutesResponse) ProtoMessage() {}

func (x *GetIntersectingRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntersectingRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetIntersectingRoutesResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{16}
}

func (x *GetIntersectingRoutesResponse) GetRoutes() []*RouteDescriptor {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetIntersectingRoutesResponse) GetCatalogVersion() uint64 {
	if x != nil {
		return x.CatalogVersion
	}
	return 0
}

type GetSplitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSplitJobRequest) Reset() {
	*x = GetSplitJobRequest{}
	mi := &file_distribution_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSplitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSplitJobRequest) ProtoMessage() {}

func (x *GetSplitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSplitJobRequest.ProtoReflect.Descriptor instead.
func (*GetSplitJobRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{17}
}

func (x *GetSplitJobRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type GetSplitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *SplitJob              `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSplitJobResponse) Reset() {
	*x = GetSplitJobResponse{}
	mi := &file_distribution_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSplitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSplitJobResponse) ProtoMessage() {}

func (x *GetSplitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSplitJobResponse.ProtoReflect.Descriptor instead.
func (*GetSplitJobResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{18}
}

func (x *GetSplitJobResponse) GetJob() *SplitJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListSplitJobsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SinceTerminalAtMs uint64                 `protobuf:"varint,1,opt,name=since_terminal_at_ms,json=sinceTerminalAtMs,proto3" json:"since_terminal_at_ms,omitempty"`
	Phase             string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	PageCursor        []byte                 `protobuf:"bytes,3,opt,name=page_cursor,json=pageCursor,proto3" json:"page_cursor,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListSplitJobsRequest) Reset() {
	*x = ListSplitJobsRequest{}
	mi := &file_distribution_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSplitJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSplitJobsRequest) ProtoMessage() {}

func (x *ListSplitJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSplitJobsRequest.ProtoReflect.Descriptor instead.
func (*ListSplitJobsRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{19}
}

func (x *ListSplitJobsRequest) GetSinceTerminalAtMs() uint64 {
	if x != nil {
		return x.SinceTerminalAtMs
	}
	return 0
}

func (x *ListSplitJobsRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ListSplitJobsRequest) GetPageCursor() []byte {
	if x != nil {
		return x.PageCursor
	}
	return nil
}

type ListSplitJobsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Jobs           []*SplitJob            `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	NextPageCursor []byte                 `protobuf:"bytes,2,opt,name=next_page_cursor,json=nextPageCursor,proto3" json:"next_page_cursor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListSplitJobsResponse) Reset() {
	*x = ListSplitJobsResponse{}
	mi := &file_distribution_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSplitJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSplitJobsResponse) ProtoMessage() {}

func (x *ListSplitJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSplitJobsResponse.ProtoReflect.Descriptor instead.
func (*ListSplitJobsResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{20}
}

func (x *ListSplitJobsResponse) GetJobs() []*SplitJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListSplitJobsResponse) GetNextPageCursor() []byte {
	if x != nil {
		return x.NextPageCursor
	}
	return nil
}

type AbandonSplitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonSplitJobRequest) Reset() {
	*x = AbandonSplitJobRequest{}
	mi := &file_distribution_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonSplitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonSplitJobRequest) ProtoMessage() {}

func (x *AbandonSplitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonSplitJobRequest.ProtoReflect.Descriptor instead.
func (*AbandonSplitJobRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{21}
}

func (x *AbandonSplitJobRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type AbandonSplitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonSplitJobResponse) Reset() {
	*x = AbandonSplitJobResponse{}
	mi := &file_distribution_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonSplitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonSplitJobResponse) ProtoMessage() {}

func (x *AbandonSplitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonSplitJobResponse.ProtoReflect.Descriptor instead.
func (*AbandonSplitJobResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{22}
}

type RetrySplitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         uint64                 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrySplitJobRequest) Reset() {
	*x = RetrySplitJobRequest{}
	mi := &file_distribution_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrySplitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrySplitJobRequest) ProtoMessage() {}

func (x *RetrySplitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrySplitJobRequest.ProtoReflect.Descriptor instead.
func (*RetrySplitJobRequest) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{23}
}

func (x *RetrySplitJobRequest) GetJobId() uint64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type RetrySplitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrySplitJobResponse) Reset() {
	*x = RetrySplitJobResponse{}
	mi := &file_distribution_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrySplitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrySplitJobResponse) ProtoMessage() {}

func (x *RetrySplitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribution_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrySplitJobResponse.ProtoReflect.Descriptor instead.
func (*RetrySplitJobResponse) Descriptor() ([]byte, []int) {
	return file_distribution_proto_rawDescGZIP(), []int{24}
}

var File_distribution_proto protoreflect.FileDescriptor

const file_distribution_proto_rawDesc = "" +
	"\n" +
	"\x12distribution.proto\"#\n" +
	"\x0fGetRouteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"^\n" +
	"\x10GetRouteResponse\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12\"\n" +
	"\rraft_group_id\x18\x03 \x01(\x04R\vraftGroupId\"\x15\n" +
	"\x13GetTimestampRequest\"4\n" +
	"\x14GetTimestampResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\"\xfe\x02\n" +
	"\x0fRouteDescriptor\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\x04R\arouteId\x12\x14\n" +
	"\x05start\x18\x02 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\fR\x03end\x12\"\n" +
	"\rraft_group_id\x18\x04 \x01(\x04R\vraftGroupId\x12!\n" +
	"\x05state\x18\x05 \x01(\x0e2\v.RouteStateR\x05state\x12&\n" +
	"\x0fparent_route_id\x18\x06 \x01(\x04R\rparentRouteId\x12 \n" +
	"\fsplit_at_hlc\x18\a \x01(\x04R\n" +
	"splitAtHlc\x128\n" +
	"\x18staged_visibility_active\x18\b \x01(\bR\x16stagedVisibilityActive\x12(\n" +
	"\x10migration_job_id\x18\t \x01(\x04R\x0emigrationJobId\x123\n" +
	"\x16min_write_ts_exclusive\x18\n" +
	" \x01(\x04R\x13minWriteTsExclusive\"\xb0\x02\n" +
	"\x17SplitJobBracketProgress\x12\x1d\n" +
	"\n" +
	"bracket_id\x18\x01 \x01(\x04R\tbracketId\x12\x16\n" +
	"\x06family\x18\x02 \x01(\rR\x06family\x127\n" +
	"\fexport_phase\x18\x03 \x01(\x0e2\x14.SplitJobExportPhaseR\vexportPhase\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\fR\x06cursor\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done\x12#\n" +
	"\rscanned_bytes\x18\x06 \x01(\x04R\fscannedBytes\x12#\n" +
	"\raccepted_rows\x18\a \x01(\x04R\facceptedRows\x12/\n" +
	"\x14last_acked_batch_seq\x18\b \x01(\x04R\x11lastAckedBatchSeq\"\xe9\f\n" +
	"\bSplitJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\x12&\n" +
	"\x0fsource_route_id\x18\x02 \x01(\x04R\rsourceRouteId\x12\x1b\n" +
	"\tsplit_key\x18\x03 \x01(\fR\bsplitKey\x12&\n" +
	"\x0ftarget_group_id\x18\x04 \x01(\x04R\rtargetGroupId\x12$\n" +
	"\x05phase\x18\x05 \x01(\x0e2\x0e.SplitJobPhaseR\x05phase\x12/\n" +
	"\vretry_phase\x18\x06 \x01(\x0e2\x0e.SplitJobPhaseR\n" +
	"retryPhase\x12<\n" +
	"\x12abandon_from_phase\x18\a \x01(\x0e2\x0e.SplitJobPhaseR\x10abandonFromPhase\x12\x1f\n" +
	"\vsnapshot_ts\x18\b \x01(\x04R\n" +
	"snapshotTs\x127\n" +
	"\x18snapshot_min_admitted_ts\x18\t \x01(\x04R\x15snapshotMinAdmittedTs\x12.\n" +
	"\x13write_tracker_armed\x18\n" +
	" \x01(\bR\x11writeTrackerArmed\x12\x1f\n" +
	"\vdelta_floor\x18\v \x01(\x04R\n" +
	"deltaFloor\x12;\n" +
	"\x1apost_fence_drain_completed\x18\f \x01(\bR\x17postFenceDrainCompleted\x12\x19\n" +
	"\bfence_ts\x18\r \x01(\x04R\afenceTs\x12'\n" +
	"\x0fcutover_version\x18\x0e \x01(\x04R\x0ecutoverVersion\x12N\n" +
	"\x18cutover_read_fence_state\x18\x0f \x01(\x0e2\x15.SplitJobBarrierStateR\x15cutoverReadFenceState\x12X\n" +
	"\x1dtarget_staged_readiness_state\x18\x10 \x01(\x0e2\x15.SplitJobBarrierStateR\x1atargetStagedReadinessState\x12M\n" +
	"$source_cutover_read_fence_ack_cursor\x18\x11 \x01(\fR\x1fsourceCutoverReadFenceAckCursor\x12J\n" +
	"\"target_staged_readiness_ack_cursor\x18\x12 \x01(\fR\x1etargetStagedReadinessAckCursor\x12\x16\n" +
	"\x06cursor\x18\x13 \x01(\fR\x06cursor\x12&\n" +
	"\x0fmax_imported_ts\x18\x14 \x01(\x04R\rmaxImportedTs\x122\n" +
	"\x15target_promotion_done\x18\x15 \x01(\bR\x13targetPromotionDone\x124\n" +
	"\x16promotion_completed_ts\x18\x16 \x01(\x04R\x14promotionCompletedTs\x122\n" +
	"\x15fence_catalog_version\x18\x17 \x01(\x04R\x13fenceCatalogVersion\x12(\n" +
	"\x10fence_ack_cursor\x18\x18 \x01(\fR\x0efenceAckCursor\x129\n" +
	"\x19source_cutover_ack_cursor\x18\x19 \x01(\fR\x16sourceCutoverAckCursor\x127\n" +
	"\x18source_read_drain_cursor\x18\x1a \x01(\fR\x15sourceReadDrainCursor\x12N\n" +
	"$target_cleared_descriptor_ack_cursor\x18\x1b \x01(\fR targetClearedDescriptorAckCursor\x12C\n" +
	"\x10bracket_progress\x18\x1c \x03(\v2\x18.SplitJobBracketProgressR\x0fbracketProgress\x125\n" +
	"\x17source_retention_pin_ts\x18\x1d \x01(\x04R\x14sourceRetentionPinTs\x12\x1d\n" +
	"\n" +
	"last_error\x18\x1e \x01(\tR\tlastError\x12\"\n" +
	"\rstarted_at_ms\x18\x1f \x01(\x03R\vstartedAtMs\x12\"\n" +
	"\rupdated_at_ms\x18  \x01(\x03R\vupdatedAtMs\x12$\n" +
	"\x0eterminal_at_ms\x18! \x01(\x03R\fterminalAtMs\"\x13\n" +
	"\x11ListRoutesRequest\"g\n" +
	"\x12ListRoutesResponse\x12'\n" +
	"\x0fcatalog_version\x18\x01 \x01(\x04R\x0ecatalogVersion\x12(\n" +
	"\x06routes\x18\x02 \x03(\v2\x10.RouteDescriptorR\x06routes\"\x85\x01\n" +
	"\x11SplitRangeRequest\x128\n" +
	"\x18expected_catalog_version\x18\x01 \x01(\x04R\x16expectedCatalogVersion\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\x04R\arouteId\x12\x1b\n" +
	"\tsplit_key\x18\x03 \x01(\fR\bsplitKey\"\x8b\x01\n" +
	"\x12SplitRangeResponse\x12'\n" +
	"\x0fcatalog_version\x18\x01 \x01(\x04R\x0ecatalogVersion\x12$\n" +
	"\x04left\x18\x02 \x01(\v2\x10.RouteDescriptorR\x04left\x12&\n" +
	"\x05right\x18\x03 \x01(\v2\x10.RouteDescriptorR\x05right\"\xb6\x02\n" +
	"\x1aStartSplitMigrationRequest\x128\n" +
	"\x18expected_catalog_version\x18\x01 \x01(\x04R\x16expectedCatalogVersion\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\x04R\arouteId\x12\x1b\n" +
	"\tsplit_key\x18\x03 \x01(\fR\bsplitKey\x12&\n" +
	"\x0ftarget_group_id\x18\x04 \x01(\x04R\rtargetGroupId\x12B\n" +
	"\aoptions\x18\x05 \x03(\v2(.StartSplitMigrationRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\x1bStartSplitMigrationResponse\x12'\n" +
	"\x0fcatalog_version\x18\x01 \x01(\x04R\x0ecatalogVersion\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x04R\x05jobId\"U\n" +
	"\x18GetRouteOwnershipRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12'\n" +
	"\x0fcatalog_version\x18\x02 \x01(\x04R\x0ecatalogVersion\"\x82\x01\n" +
	"\x19GetRouteOwnershipResponse\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.RouteDescriptorR\x05route\x12'\n" +
	"\x0fcatalog_version\x18\x02 \x01(\x04R\x0ecatalogVersion\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"o\n" +
	"\x1cGetIntersectingRoutesRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\fR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\fR\x03end\x12'\n" +
	"\x0fcatalog_version\x18\x03 \x01(\x04R\x0ecatalogVersion\"r\n" +
	"\x1dGetIntersectingRoutesResponse\x12(\n" +
	"\x06routes\x18\x01 \x03(\v2\x10.RouteDescriptorR\x06routes\x12'\n" +
	"\x0fcatalog_version\x18\x02 \x01(\x04R\x0ecatalogVersion\"+\n" +
	"\x12GetSplitJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"2\n" +
	"\x13GetSplitJobResponse\x12\x1b\n" +
	"\x03job\x18\x01 \x01(\v2\t.SplitJobR\x03job\"~\n" +
	"\x14ListSplitJobsRequest\x12/\n" +
	"\x14since_terminal_at_ms\x18\x01 \x01(\x04R\x11sinceTerminalAtMs\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x1f\n" +
	"\vpage_cursor\x18\x03 \x01(\fR\n" +
	"pageCursor\"`\n" +
	"\x15ListSplitJobsResponse\x12\x1d\n" +
	"\x04jobs\x18\x01 \x03(\v2\t.SplitJobR\x04jobs\x12(\n" +
	"\x10next_page_cursor\x18\x02 \x01(\fR\x0enextPageCursor\"/\n" +
	"\x16AbandonSplitJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"\x19\n" +
	"\x17AbandonSplitJobResponse\"-\n" +
	"\x14RetrySplitJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x04R\x05jobId\"\x17\n" +
	"\x15RetrySplitJobResponse*\xa3\x01\n" +
	"\n" +
	"RouteState\x12\x1b\n" +
	"\x17ROUTE_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ROUTE_STATE_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18ROUTE_STATE_WRITE_FENCED\x10\x02\x12 \n" +
	"\x1cROUTE_STATE_MIGRATING_SOURCE\x10\x03\x12 \n" +
	"\x1cROUTE_STATE_MIGRATING_TARGET\x10\x04*\xce\x02\n" +
	"\rSplitJobPhase\x12\x18\n" +
	"\x14SPLIT_JOB_PHASE_NONE\x10\x00\x12\x1b\n" +
	"\x17SPLIT_JOB_PHASE_PLANNED\x10\x01\x12\x1c\n" +
	"\x18SPLIT_JOB_PHASE_BACKFILL\x10\x02\x12\x19\n" +
	"\x15SPLIT_JOB_PHASE_FENCE\x10\x03\x12\x1e\n" +
	"\x1aSPLIT_JOB_PHASE_DELTA_COPY\x10\x04\x12\x1b\n" +
	"\x17SPLIT_JOB_PHASE_CUTOVER\x10\x05\x12\x1b\n" +
	"\x17SPLIT_JOB_PHASE_CLEANUP\x10\x06\x12\x18\n" +
	"\x14SPLIT_JOB_PHASE_DONE\x10\a\x12\x1a\n" +
	"\x16SPLIT_JOB_PHASE_FAILED\x10\b\x12\x1e\n" +
	"\x1aSPLIT_JOB_PHASE_ABANDONING\x10\t\x12\x1d\n" +
	"\x19SPLIT_JOB_PHASE_ABANDONED\x10\n" +
	"*\xa5\x01\n" +
	"\x14SplitJobBarrierState\x12 \n" +
	"\x1cSPLIT_JOB_BARRIER_STATE_NONE\x10\x00\x12\"\n" +
	"\x1eSPLIT_JOB_BARRIER_STATE_ARMING\x10\x01\x12!\n" +
	"\x1dSPLIT_JOB_BARRIER_STATE_ARMED\x10\x02\x12$\n" +
	" SPLIT_JOB_BARRIER_STATE_CLEARING\x10\x03*\x82\x01\n" +
	"\x13SplitJobExportPhase\x12\x1f\n" +
	"\x1bSPLIT_JOB_EXPORT_PHASE_NONE\x10\x00\x12#\n" +
	"\x1fSPLIT_JOB_EXPORT_PHASE_BACKFILL\x10\x01\x12%\n" +
	"!SPLIT_JOB_EXPORT_PHASE_DELTA_COPY\x10\x022\xf6\x05\n" +
	"\fDistribution\x121\n" +
	"\bGetRoute\x12\x10.GetRouteRequest\x1a\x11.GetRouteResponse\"\x00\x12=\n" +
	"\fGetTimestamp\x12\x14.GetTimestampRequest\x1a\x15.GetTimestampResponse\"\x00\x127\n" +
	"\n" +
	"ListRoutes\x12\x12.ListRoutesRequest\x1a\x13.ListRoutesResponse\"\x00\x127\n" +
	"\n" +
	"SplitRange\x12\x12.SplitRangeRequest\x1a\x13.SplitRangeResponse\"\x00\x12R\n" +
	"\x13StartSplitMigration\x12\x1b.StartSplitMigrationRequest\x1a\x1c.StartSplitMigrationResponse\"\x00\x12L\n" +
	"\x11GetRouteOwnership\x12\x19.GetRouteOwnershipRequest\x1a\x1a.GetRouteOwnershipResponse\"\x00\x12X\n" +
	"\x15GetIntersectingRoutes\x12\x1d.GetIntersectingRoutesRequest\x1a\x1e.GetIntersectingRoutesResponse\"\x00\x12:\n" +
	"\vGetSplitJob\x12\x13.GetSplitJobRequest\x1a\x14.GetSplitJobResponse\"\x00\x12@\n" +
	"\rListSplitJobs\x12\x15.ListSplitJobsRequest\x1a\x16.ListSplitJobsResponse\"\x00\x12F\n" +
	"\x0fAbandonSplitJob\x12\x17.AbandonSplitJobRequest\x1a\x18.AbandonSplitJobResponse\"\x00\x12@\n" +
	"\rRetrySplitJob\x12\x15.RetrySplitJobRequest\x1a\x16.RetrySplitJobResponse\"\x00B#Z!github.com/bootjp/elastickv/protob\x06proto3"

var (
	file_distribution_proto_rawDescOnce sync.Once
	file_distribution_proto_rawDescData []byte
)

func file_distribution_proto_rawDescGZIP() []byte {
	file_distribution_proto_rawDescOnce.Do(func() {
		file_distribution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distribution_proto_rawDesc), len(file_distribution_proto_rawDesc)))
	})
	return file_distribution_proto_rawDescData
}

var file_distribution_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_distribution_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_distribution_proto_goTypes = []any{
	(RouteState)(0),                       // 0: RouteState
	(SplitJobPhase)(0),                    // 1: SplitJobPhase
	(SplitJobBarrierState)(0),             // 2: SplitJobBarrierState
	(SplitJobExportPhase)(0),              // 3: SplitJobExportPhase
	(*GetRouteRequest)(nil),               // 4: GetRouteRequest
	(*GetRouteResponse)(nil),              // 5: GetRouteResponse
	(*GetTimestampRequest)(nil),           // 6: GetTimestampRequest
	(*GetTimestampResponse)(nil),          // 7: GetTimestampResponse
	(*RouteDescriptor)(nil),               // 8: RouteDescriptor
	(*SplitJobBracketProgress)(nil),       // 9: SplitJobBracketProgress
	(*SplitJob)(nil),                      // 10: SplitJob
	(*ListRoutesRequest)(nil),             // 11: ListRoutesRequest
	(*ListRoutesResponse)(nil),            // 12: ListRoutesResponse
	(*SplitRangeRequest)(nil),             // 13: SplitRangeRequest
	(*SplitRangeResponse)(nil),            // 14: SplitRangeResponse
	(*StartSplitMigrationRequest)(nil),    // 15: StartSplitMigrationRequest
	(*StartSplitMigrationResponse)(nil),   // 16: StartSplitMigrationResponse
	(*GetRouteOwnershipRequest)(nil),      // 17: GetRouteOwnershipRequest
	(*GetRouteOwnershipResponse)(nil),     // 18: GetRouteOwnershipResponse
	(*GetIntersectingRoutesRequest)(nil),  // 19: GetIntersectingRoutesRequest
	(*GetIntersectingRoutesResponse)(nil), // 20: GetIntersectingRoutesResponse
	(*GetSplitJobRequest)(nil),            // 21: GetSplitJobRequest
	(*GetSplitJobResponse)(nil),           // 22: GetSplitJobResponse
	(*ListSplitJobsRequest)(nil),          // 23: ListSplitJobsRequest
	(*ListSplitJobsResponse)(nil),         // 24: ListSplitJobsResponse
	(*AbandonSplitJobRequest)(nil),        // 25: AbandonSplitJobRequest
	(*AbandonSplitJobResponse)(nil),       // 26: AbandonSplitJobResponse
	(*RetrySplitJobRequest)(nil),          // 27: RetrySplitJobRequest
	(*RetrySplitJobResponse)(nil),         // 28: RetrySplitJobResponse
	nil,                                   // 29: StartSplitMigrationRequest.OptionsEntry
}
var file_distribution_proto_depIdxs = []int32{
	0,  // 0: RouteDescriptor.state:type_name -> RouteState
	3,  // 1: SplitJobBracketProgress.export_phase:type_name -> SplitJobExportPhase
	1,  // 2: SplitJob.phase:type_name -> SplitJobPhase
	1,  // 3: SplitJob.retry_phase:type_name -> SplitJobPhase
	1,  // 4: SplitJob.abandon_from_phase:type_name -> SplitJobPhase
	2,  // 5: SplitJob.cutover_read_fence_state:type_name -> SplitJobBarrierState
	2,  // 6: SplitJob.target_staged_readiness_state:type_name -> SplitJobBarrierState
	9,  // 7: SplitJob.bracket_progress:type_name -> SplitJobBracketProgress
	8,  // 8: ListRoutesResponse.routes:type_name -> RouteDescriptor
	8,  // 9: SplitRangeResponse.left:type_name -> RouteDescriptor
	8,  // 10: SplitRangeResponse.right:type_name -> RouteDescriptor
	29, // 11: StartSplitMigrationRequest.options:type_name -> StartSplitMigrationRequest.OptionsEntry
	8,  // 12: GetRouteOwnershipResponse.route:type_name -> RouteDescriptor
	8,  // 13: GetIntersectingRoutesResponse.routes:type_name -> RouteDescriptor
	10, // 14: GetSplitJobResponse.job:type_name -> SplitJob
	10, // 15: ListSplitJobsResponse.jobs:type_name -> SplitJob
	4,  // 16: Distribution.GetRoute:input_type -> GetRouteRequest
	6,  // 17: Distribution.GetTimestamp:input_type -> GetTimestampRequest
	11, // 18: Distribution.ListRoutes:input_type -> ListRoutesRequest
	13, // 19: Distribution.SplitRange:input_type -> SplitRangeRequest
	15, // 20: Distribution.StartSplitMigration:input_type -> StartSplitMigrationRequest
	17, // 21: Distribution.GetRouteOwnership:input_type -> GetRouteOwnershipRequest
	19, // 22: Distribution.GetIntersectingRoutes:input_type -> GetIntersectingRoutesRequest
	21, // 23: Distribution.GetSplitJob:input_type -> GetSplitJobRequest
	23, // 24: Distribution.ListSplitJobs:input_type -> ListSplitJobsRequest
	25, // 25: Distribution.AbandonSplitJob:input_type -> AbandonSplitJobRequest
	27, // 26: Distribution.RetrySplitJob:input_type -> RetrySplitJobRequest
	5,  // 27: Distribution.GetRoute:output_type -> GetRouteResponse
	7,  // 28: Distribution.GetTimestamp:output_type -> GetTimestampResponse
	12, // 29: Distribution.ListRoutes:output_type -> ListRoutesResponse
	14, // 30: Distribution.SplitRange:output_type -> SplitRangeResponse
	16, // 31: Distribution.StartSplitMigration:output_type -> StartSplitMigrationResponse
	18, // 32: Distribution.GetRouteOwnership:output_type -> GetRouteOwnershipResponse
	20, // 33: Distribution.GetIntersectingRoutes:output_type -> GetIntersectingRoutesResponse
	22, // 34: Distribution.GetSplitJob:output_type -> GetSplitJobResponse
	24, // 35: Distribution.ListSplitJobs:output_type -> ListSplitJobsResponse
	26, // 36: Distribution.AbandonSplitJob:output_type -> AbandonSplitJobResponse
	28, // 37: Distribution.RetrySplitJob:output_type -> RetrySplitJobResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_distribution_proto_init() }
func file_distribution_proto_init() {
	if File_distribution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distribution_proto_rawDesc), len(file_distribution_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distribution_proto_goTypes,
		DependencyIndexes: file_distribution_proto_depIdxs,
		EnumInfos:         file_distribution_proto_enumTypes,
		MessageInfos:      file_distribution_proto_msgTypes,
	}.Build()
	File_distribution_proto = out.File
	file_distribution_proto_goTypes = nil
	file_distribution_proto_depIdxs = nil
}
