// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dynamodb_internal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamoKeySchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HashKey       string                 `protobuf:"bytes,1,opt,name=hash_key,json=hashKey,proto3" json:"hash_key,omitempty"`
	RangeKey      string                 `protobuf:"bytes,2,opt,name=range_key,json=rangeKey,proto3" json:"range_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoKeySchema) Reset() {
	*x = DynamoKeySchema{}
	mi := &file_dynamodb_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoKeySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoKeySchema) ProtoMessage() {}

func (x *DynamoKeySchema) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoKeySchema.ProtoReflect.Descriptor instead.
func (*DynamoKeySchema) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{0}
}

func (x *DynamoKeySchema) GetHashKey() string {
	if x != nil {
		return x.HashKey
	}
	return ""
}

func (x *DynamoKeySchema) GetRangeKey() string {
	if x != nil {
		return x.RangeKey
	}
	return ""
}

type DynamoGSIProjection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProjectionType   string                 `protobuf:"bytes,1,opt,name=projection_type,json=projectionType,proto3" json:"projection_type,omitempty"`
	NonKeyAttributes []string               `protobuf:"bytes,2,rep,name=non_key_attributes,json=nonKeyAttributes,proto3" json:"non_key_attributes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DynamoGSIProjection) Reset() {
	*x = DynamoGSIProjection{}
	mi := &file_dynamodb_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoGSIProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoGSIProjection) ProtoMessage() {}

func (x *DynamoGSIProjection) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoGSIProjection.ProtoReflect.Descriptor instead.
func (*DynamoGSIProjection) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{1}
}

func (x *DynamoGSIProjection) GetProjectionType() string {
	if x != nil {
		return x.ProjectionType
	}
	return ""
}

func (x *DynamoGSIProjection) GetNonKeyAttributes() []string {
	if x != nil {
		return x.NonKeyAttributes
	}
	return nil
}

type DynamoGlobalSecondaryIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeySchema     *DynamoKeySchema       `protobuf:"bytes,1,opt,name=key_schema,json=keySchema,proto3" json:"key_schema,omitempty"`
	Projection    *DynamoGSIProjection   `protobuf:"bytes,2,opt,name=projection,proto3" json:"projection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoGlobalSecondaryIndex) Reset() {
	*x = DynamoGlobalSecondaryIndex{}
	mi := &file_dynamodb_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoGlobalSecondaryIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoGlobalSecondaryIndex) ProtoMessage() {}

func (x *DynamoGlobalSecondaryIndex) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoGlobalSecondaryIndex.ProtoReflect.Descriptor instead.
func (*DynamoGlobalSecondaryIndex) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{2}
}

func (x *DynamoGlobalSecondaryIndex) GetKeySchema() *DynamoKeySchema {
	if x != nil {
		return x.KeySchema
	}
	return nil
}

func (x *DynamoGlobalSecondaryIndex) GetProjection() *DynamoGSIProjection {
	if x != nil {
		return x.Projection
	}
	return nil
}

type DynamoTableSchema struct {
	state                   protoimpl.MessageState                 `protogen:"open.v1"`
	TableName               string                                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	AttributeDefinitions    map[string]string                      `protobuf:"bytes,2,rep,name=attribute_definitions,json=attributeDefinitions,proto3" json:"attribute_definitions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PrimaryKey              *DynamoKeySchema                       `protobuf:"bytes,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	GlobalSecondaryIndexes  map[string]*DynamoGlobalSecondaryIndex `protobuf:"bytes,4,rep,name=global_secondary_indexes,json=globalSecondaryIndexes,proto3" json:"global_secondary_indexes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	KeyEncodingVersion      uint64                                 `protobuf:"varint,5,opt,name=key_encoding_version,json=keyEncodingVersion,proto3" json:"key_encoding_version,omitempty"`
	MigratingFromGeneration uint64                                 `protobuf:"varint,6,opt,name=migrating_from_generation,json=migratingFromGeneration,proto3" json:"migrating_from_generation,omitempty"`
	Generation              uint64                                 `protobuf:"varint,7,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DynamoTableSchema) Reset() {
	*x = DynamoTableSchema{}
	mi := &file_dynamodb_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoTableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoTableSchema) ProtoMessage() {}

func (x *DynamoTableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoTableSchema.ProtoReflect.Descriptor instead.
func (*DynamoTableSchema) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{3}
}

func (x *DynamoTableSchema) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DynamoTableSchema) GetAttributeDefinitions() map[string]string {
	if x != nil {
		return x.AttributeDefinitions
	}
	return nil
}

func (x *DynamoTableSchema) GetPrimaryKey() *DynamoKeySchema {
	if x != nil {
		return x.PrimaryKey
	}
	return nil
}

func (x *DynamoTableSchema) GetGlobalSecondaryIndexes() map[string]*DynamoGlobalSecondaryIndex {
	if x != nil {
		return x.GlobalSecondaryIndexes
	}
	return nil
}

func (x *DynamoTableSchema) GetKeyEncodingVersion() uint64 {
	if x != nil {
		return x.KeyEncodingVersion
	}
	return 0
}

func (x *DynamoTableSchema) GetMigratingFromGeneration() uint64 {
	if x != nil {
		return x.MigratingFromGeneration
	}
	return 0
}

func (x *DynamoTableSchema) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type DynamoStringSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoStringSet) Reset() {
	*x = DynamoStringSet{}
	mi := &file_dynamodb_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoStringSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoStringSet) ProtoMessage() {}

func (x *DynamoStringSet) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoStringSet.ProtoReflect.Descriptor instead.
func (*DynamoStringSet) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{4}
}

func (x *DynamoStringSet) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type DynamoNumberSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoNumberSet) Reset() {
	*x = DynamoNumberSet{}
	mi := &file_dynamodb_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoNumberSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoNumberSet) ProtoMessage() {}

func (x *DynamoNumberSet) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoNumberSet.ProtoReflect.Descriptor instead.
func (*DynamoNumberSet) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{5}
}

func (x *DynamoNumberSet) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type DynamoBinarySet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoBinarySet) Reset() {
	*x = DynamoBinarySet{}
	mi := &file_dynamodb_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoBinarySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoBinarySet) ProtoMessage() {}

func (x *DynamoBinarySet) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoBinarySet.ProtoReflect.Descriptor instead.
func (*DynamoBinarySet) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{6}
}

func (x *DynamoBinarySet) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type DynamoAttributeValueList struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Values        []*DynamoAttributeValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoAttributeValueList) Reset() {
	*x = DynamoAttributeValueList{}
	mi := &file_dynamodb_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoAttributeValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoAttributeValueList) ProtoMessage() {}

func (x *DynamoAttributeValueList) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoAttributeValueList.ProtoReflect.Descriptor instead.
func (*DynamoAttributeValueList) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{7}
}

func (x *DynamoAttributeValueList) GetValues() []*DynamoAttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type DynamoAttributeValueMap struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Values        map[string]*DynamoAttributeValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoAttributeValueMap) Reset() {
	*x = DynamoAttributeValueMap{}
	mi := &file_dynamodb_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoAttributeValueMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoAttributeValueMap) ProtoMessage() {}

func (x *DynamoAttributeValueMap) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoAttributeValueMap.ProtoReflect.Descriptor instead.
func (*DynamoAttributeValueMap) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{8}
}

func (x *DynamoAttributeValueMap) GetValues() map[string]*DynamoAttributeValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type DynamoAttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*DynamoAttributeValue_S
	//	*DynamoAttributeValue_N
	//	*DynamoAttributeValue_B
	//	*DynamoAttributeValue_BoolValue
	//	*DynamoAttributeValue_NullValue
	//	*DynamoAttributeValue_Ss
	//	*DynamoAttributeValue_Ns
	//	*DynamoAttributeValue_Bs
	//	*DynamoAttributeValue_L
	//	*DynamoAttributeValue_M
	Value         isDynamoAttributeValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoAttributeValue) Reset() {
	*x = DynamoAttributeValue{}
	mi := &file_dynamodb_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoAttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoAttributeValue) ProtoMessage() {}

func (x *DynamoAttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoAttributeValue.ProtoReflect.Descriptor instead.
func (*DynamoAttributeValue) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{9}
}

func (x *DynamoAttributeValue) GetValue() isDynamoAttributeValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DynamoAttributeValue) GetS() string {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *DynamoAttributeValue) GetN() string {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_N); ok {
			return x.N
		}
	}
	return ""
}

func (x *DynamoAttributeValue) GetB() []byte {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_B); ok {
			return x.B
		}
	}
	return nil
}

func (x *DynamoAttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *DynamoAttributeValue) GetNullValue() bool {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_NullValue); ok {
			return x.NullValue
		}
	}
	return false
}

func (x *DynamoAttributeValue) GetSs() *DynamoStringSet {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_Ss); ok {
			return x.Ss
		}
	}
	return nil
}

func (x *DynamoAttributeValue) GetNs() *DynamoNumberSet {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_Ns); ok {
			return x.Ns
		}
	}
	return nil
}

func (x *DynamoAttributeValue) GetBs() *DynamoBinarySet {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_Bs); ok {
			return x.Bs
		}
	}
	return nil
}

func (x *DynamoAttributeValue) GetL() *DynamoAttributeValueList {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_L); ok {
			return x.L
		}
	}
	return nil
}

func (x *DynamoAttributeValue) GetM() *DynamoAttributeValueMap {
	if x != nil {
		if x, ok := x.Value.(*DynamoAttributeValue_M); ok {
			return x.M
		}
	}
	return nil
}

type isDynamoAttributeValue_Value interface {
	isDynamoAttributeValue_Value()
}

type DynamoAttributeValue_S struct {
	S string `protobuf:"bytes,1,opt,name=s,proto3,oneof"`
}

type DynamoAttributeValue_N struct {
	N string `protobuf:"bytes,2,opt,name=n,proto3,oneof"`
}

type DynamoAttributeValue_B struct {
	B []byte `protobuf:"bytes,3,opt,name=b,proto3,oneof"`
}

type DynamoAttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type DynamoAttributeValue_NullValue struct {
	NullValue bool `protobuf:"varint,5,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type DynamoAttributeValue_Ss struct {
	Ss *DynamoStringSet `protobuf:"bytes,6,opt,name=ss,proto3,oneof"`
}

type DynamoAttributeValue_Ns struct {
	Ns *DynamoNumberSet `protobuf:"bytes,7,opt,name=ns,proto3,oneof"`
}

type DynamoAttributeValue_Bs struct {
	Bs *DynamoBinarySet `protobuf:"bytes,8,opt,name=bs,proto3,oneof"`
}

type DynamoAttributeValue_L struct {
	L *DynamoAttributeValueList `protobuf:"bytes,9,opt,name=l,proto3,oneof"`
}

type DynamoAttributeValue_M struct {
	M *DynamoAttributeValueMap `protobuf:"bytes,10,opt,name=m,proto3,oneof"`
}

func (*DynamoAttributeValue_S) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_N) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_B) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_BoolValue) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_NullValue) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_Ss) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_Ns) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_Bs) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_L) isDynamoAttributeValue_Value() {}

func (*DynamoAttributeValue_M) isDynamoAttributeValue_Value() {}

type DynamoItem struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Attributes    map[string]*DynamoAttributeValue `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoItem) Reset() {
	*x = DynamoItem{}
	mi := &file_dynamodb_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoItem) ProtoMessage() {}

func (x *DynamoItem) ProtoReflect() protoreflect.Message {
	mi := &file_dynamodb_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoItem.ProtoReflect.Descriptor instead.
func (*DynamoItem) Descriptor() ([]byte, []int) {
	return file_dynamodb_internal_proto_rawDescGZIP(), []int{10}
}

func (x *DynamoItem) GetAttributes() map[string]*DynamoAttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_dynamodb_internal_proto protoreflect.FileDescriptor

const file_dynamodb_internal_proto_rawDesc = "" +
	"\n" +
	"\x17dynamodb_internal.proto\"I\n" +
	"\x0fDynamoKeySchema\x12\x19\n" +
	"\bhash_key\x18\x01 \x01(\tR\ahashKey\x12\x1b\n" +
	"\trange_key\x18\x02 \x01(\tR\brangeKey\"l\n" +
	"\x13DynamoGSIProjection\x12'\n" +
	"\x0fprojection_type\x18\x01 \x01(\tR\x0eprojectionType\x12,\n" +
	"\x12non_key_attributes\x18\x02 \x03(\tR\x10nonKeyAttributes\"\x83\x01\n" +
	"\x1aDynamoGlobalSecondaryIndex\x12/\n" +
	"\n" +
	"key_schema\x18\x01 \x01(\v2\x10.DynamoKeySchemaR\tkeySchema\x124\n" +
	"\n" +
	"projection\x18\x02 \x01(\v2\x14.DynamoGSIProjectionR\n" +
	"projection\"\xf1\x04\n" +
	"\x11DynamoTableSchema\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12a\n" +
	"\x15attribute_definitions\x18\x02 \x03(\v2,.DynamoTableSchema.AttributeDefinitionsEntryR\x14attributeDefinitions\x121\n" +
	"\vprimary_key\x18\x03 \x01(\v2\x10.DynamoKeySchemaR\n" +
	"primaryKey\x12h\n" +
	"\x18global_secondary_indexes\x18\x04 \x03(\v2..DynamoTableSchema.GlobalSecondaryIndexesEntryR\x16globalSecondaryIndexes\x120\n" +
	"\x14key_encoding_version\x18\x05 \x01(\x04R\x12keyEncodingVersion\x12:\n" +
	"\x19migrating_from_generation\x18\x06 \x01(\x04R\x17migratingFromGeneration\x12\x1e\n" +
	"\n" +
	"generation\x18\a \x01(\x04R\n" +
	"generation\x1aG\n" +
	"\x19AttributeDefinitionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1af\n" +
	"\x1bGlobalSecondaryIndexesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.DynamoGlobalSecondaryIndexR\x05value:\x028\x01\")\n" +
	"\x0fDynamoStringSet\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\")\n" +
	"\x0fDynamoNumberSet\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\")\n" +
	"\x0fDynamoBinarySet\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"I\n" +
	"\x18DynamoAttributeValueList\x12-\n" +
	"\x06values\x18\x01 \x03(\v2\x15.DynamoAttributeValueR\x06values\"\xa9\x01\n" +
	"\x17DynamoAttributeValueMap\x12<\n" +
	"\x06values\x18\x01 \x03(\v2$.DynamoAttributeValueMap.ValuesEntryR\x06values\x1aP\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.DynamoAttributeValueR\x05value:\x028\x01\"\xd2\x02\n" +
	"\x14DynamoAttributeValue\x12\x0e\n" +
	"\x01s\x18\x01 \x01(\tH\x00R\x01s\x12\x0e\n" +
	"\x01n\x18\x02 \x01(\tH\x00R\x01n\x12\x0e\n" +
	"\x01b\x18\x03 \x01(\fH\x00R\x01b\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"null_value\x18\x05 \x01(\bH\x00R\tnullValue\x12\"\n" +
	"\x02ss\x18\x06 \x01(\v2\x10.DynamoStringSetH\x00R\x02ss\x12\"\n" +
	"\x02ns\x18\a \x01(\v2\x10.DynamoNumberSetH\x00R\x02ns\x12\"\n" +
	"\x02bs\x18\b \x01(\v2\x10.DynamoBinarySetH\x00R\x02bs\x12)\n" +
	"\x01l\x18\t \x01(\v2\x19.DynamoAttributeValueListH\x00R\x01l\x12(\n" +
	"\x01m\x18\n" +
	" \x01(\v2\x18.DynamoAttributeValueMapH\x00R\x01mB\a\n" +
	"\x05value\"\x9f\x01\n" +
	"\n" +
	"DynamoItem\x12;\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\x1b.DynamoItem.AttributesEntryR\n" +
	"attributes\x1aT\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.DynamoAttributeValueR\x05value:\x028\x01B#Z!github.com/bootjp/elastickv/protob\x06proto3"

var (
	file_dynamodb_internal_proto_rawDescOnce sync.Once
	file_dynamodb_internal_proto_rawDescData []byte
)

func file_dynamodb_internal_proto_rawDescGZIP() []byte {
	file_dynamodb_internal_proto_rawDescOnce.Do(func() {
		file_dynamodb_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamodb_internal_proto_rawDesc), len(file_dynamodb_internal_proto_rawDesc)))
	})
	return file_dynamodb_internal_proto_rawDescData
}

var file_dynamodb_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_dynamodb_internal_proto_goTypes = []any{
	(*DynamoKeySchema)(nil),            // 0: DynamoKeySchema
	(*DynamoGSIProjection)(nil),        // 1: DynamoGSIProjection
	(*DynamoGlobalSecondaryIndex)(nil), // 2: DynamoGlobalSecondaryIndex
	(*DynamoTableSchema)(nil),          // 3: DynamoTableSchema
	(*DynamoStringSet)(nil),            // 4: DynamoStringSet
	(*DynamoNumberSet)(nil),            // 5: DynamoNumberSet
	(*DynamoBinarySet)(nil),            // 6: DynamoBinarySet
	(*DynamoAttributeValueList)(nil),   // 7: DynamoAttributeValueList
	(*DynamoAttributeValueMap)(nil),    // 8: DynamoAttributeValueMap
	(*DynamoAttributeValue)(nil),       // 9: DynamoAttributeValue
	(*DynamoItem)(nil),                 // 10: DynamoItem
	nil,                                // 11: DynamoTableSchema.AttributeDefinitionsEntry
	nil,                                // 12: DynamoTableSchema.GlobalSecondaryIndexesEntry
	nil,                                // 13: DynamoAttributeValueMap.ValuesEntry
	nil,                                // 14: DynamoItem.AttributesEntry
}
var file_dynamodb_internal_proto_depIdxs = []int32{
	0,  // 0: DynamoGlobalSecondaryIndex.key_schema:type_name -> DynamoKeySchema
	1,  // 1: DynamoGlobalSecondaryIndex.projection:type_name -> DynamoGSIProjection
	11, // 2: DynamoTableSchema.attribute_definitions:type_name -> DynamoTableSchema.AttributeDefinitionsEntry
	0,  // 3: DynamoTableSchema.primary_key:type_name -> DynamoKeySchema
	12, // 4: DynamoTableSchema.global_secondary_indexes:type_name -> DynamoTableSchema.GlobalSecondaryIndexesEntry
	9,  // 5: DynamoAttributeValueList.values:type_name -> DynamoAttributeValue
	13, // 6: DynamoAttributeValueMap.values:type_name -> DynamoAttributeValueMap.ValuesEntry
	4,  // 7: DynamoAttributeValue.ss:type_name -> DynamoStringSet
	5,  // 8: DynamoAttributeValue.ns:type_name -> DynamoNumberSet
	6,  // 9: DynamoAttributeValue.bs:type_name -> DynamoBinarySet
	7,  // 10: DynamoAttributeValue.l:type_name -> DynamoAttributeValueList
	8,  // 11: DynamoAttributeValue.m:type_name -> DynamoAttributeValueMap
	14, // 12: DynamoItem.attributes:type_name -> DynamoItem.AttributesEntry
	2,  // 13: DynamoTableSchema.GlobalSecondaryIndexesEntry.value:type_name -> DynamoGlobalSecondaryIndex
	9,  // 14: DynamoAttributeValueMap.ValuesEntry.value:type_name -> DynamoAttributeValue
	9,  // 15: DynamoItem.AttributesEntry.value:type_name -> DynamoAttributeValue
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_dynamodb_internal_proto_init() }
func file_dynamodb_internal_proto_init() {
	if File_dynamodb_internal_proto != nil {
		return
	}
	file_dynamodb_internal_proto_msgTypes[9].OneofWrappers = []any{
		(*DynamoAttributeValue_S)(nil),
		(*DynamoAttributeValue_N)(nil),
		(*DynamoAttributeValue_B)(nil),
		(*DynamoAttributeValue_BoolValue)(nil),
		(*DynamoAttributeValue_NullValue)(nil),
		(*DynamoAttributeValue_Ss)(nil),
		(*DynamoAttributeValue_Ns)(nil),
		(*DynamoAttributeValue_Bs)(nil),
		(*DynamoAttributeValue_L)(nil),
		(*DynamoAttributeValue_M)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamodb_internal_proto_rawDesc), len(file_dynamodb_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dynamodb_internal_proto_goTypes,
		DependencyIndexes: file_dynamodb_internal_proto_depIdxs,
		MessageInfos:      file_dynamodb_internal_proto_msgTypes,
	}.Build()
	File_dynamodb_internal_proto = out.File
	file_dynamodb_internal_proto_goTypes = nil
	file_dynamodb_internal_proto_depIdxs = nil
}
