// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: encryption_admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RotateDEKRequest_Purpose int32

const (
	RotateDEKRequest_PURPOSE_UNSPECIFIED RotateDEKRequest_Purpose = 0
	RotateDEKRequest_PURPOSE_STORAGE     RotateDEKRequest_Purpose = 1
	RotateDEKRequest_PURPOSE_RAFT        RotateDEKRequest_Purpose = 2
)

// Enum value maps for RotateDEKRequest_Purpose.
var (
	RotateDEKRequest_Purpose_name = map[int32]string{
		0: "PURPOSE_UNSPECIFIED",
		1: "PURPOSE_STORAGE",
		2: "PURPOSE_RAFT",
	}
	RotateDEKRequest_Purpose_value = map[string]int32{
		"PURPOSE_UNSPECIFIED": 0,
		"PURPOSE_STORAGE":     1,
		"PURPOSE_RAFT":        2,
	}
)

func (x RotateDEKRequest_Purpose) Enum() *RotateDEKRequest_Purpose {
	p := new(RotateDEKRequest_Purpose)
	*p = x
	return p
}

func (x RotateDEKRequest_Purpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RotateDEKRequest_Purpose) Descriptor() protoreflect.EnumDescriptor {
	return file_encryption_admin_proto_enumTypes[0].Descriptor()
}

func (RotateDEKRequest_Purpose) Type() protoreflect.EnumType {
	return &file_encryption_admin_proto_enumTypes[0]
}

func (x RotateDEKRequest_Purpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RotateDEKRequest_Purpose.Descriptor instead.
func (RotateDEKRequest_Purpose) EnumDescriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{6, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_encryption_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{0}
}

// CapabilityReport mirrors §6.1 admin.go's CapabilityReport. Served
// on every node regardless of leadership state. A node that has
// never run with --encryption-enabled returns encryption_capable=false
// with local_epoch=0 and full_node_id=0, and the cutover command
// refuses with ErrCapabilityCheckFailed so the empty epoch never
// reaches the writer registry.
type CapabilityReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EncryptionCapable bool                   `protobuf:"varint,1,opt,name=encryption_capable,json=encryptionCapable,proto3" json:"encryption_capable,omitempty"`
	BuildSha          string                 `protobuf:"bytes,2,opt,name=build_sha,json=buildSha,proto3" json:"build_sha,omitempty"`
	SidecarPresent    bool                   `protobuf:"varint,3,opt,name=sidecar_present,json=sidecarPresent,proto3" json:"sidecar_present,omitempty"`
	FullNodeId        uint64                 `protobuf:"varint,4,opt,name=full_node_id,json=fullNodeId,proto3" json:"full_node_id,omitempty"`
	LocalEpoch        uint32                 `protobuf:"varint,5,opt,name=local_epoch,json=localEpoch,proto3" json:"local_epoch,omitempty"` // MUST be <= 0xFFFF on the wire.
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CapabilityReport) Reset() {
	*x = CapabilityReport{}
	mi := &file_encryption_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityReport) ProtoMessage() {}

func (x *CapabilityReport) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityReport.ProtoReflect.Descriptor instead.
func (*CapabilityReport) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilityReport) GetEncryptionCapable() bool {
	if x != nil {
		return x.EncryptionCapable
	}
	return false
}

func (x *CapabilityReport) GetBuildSha() string {
	if x != nil {
		return x.BuildSha
	}
	return ""
}

func (x *CapabilityReport) GetSidecarPresent() bool {
	if x != nil {
		return x.SidecarPresent
	}
	return false
}

func (x *CapabilityReport) GetFullNodeId() uint64 {
	if x != nil {
		return x.FullNodeId
	}
	return 0
}

func (x *CapabilityReport) GetLocalEpoch() uint32 {
	if x != nil {
		return x.LocalEpoch
	}
	return 0
}

// SidecarStateReport is the §5.5 compaction-fallback RPC. Served on
// every node but the cutover-recovery flow only consults the
// leader's response. wrapped_deks_by_id covers every unretired DEK.
type SidecarStateReport struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	WrappedDeksById          map[uint32][]byte      `protobuf:"bytes,1,rep,name=wrapped_deks_by_id,json=wrappedDeksById,proto3" json:"wrapped_deks_by_id,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ActiveStorageId          uint32                 `protobuf:"varint,2,opt,name=active_storage_id,json=activeStorageId,proto3" json:"active_storage_id,omitempty"`
	ActiveRaftId             uint32                 `protobuf:"varint,3,opt,name=active_raft_id,json=activeRaftId,proto3" json:"active_raft_id,omitempty"`
	StorageEnvelopeActive    bool                   `protobuf:"varint,4,opt,name=storage_envelope_active,json=storageEnvelopeActive,proto3" json:"storage_envelope_active,omitempty"`
	RaftEnvelopeCutoverIndex uint64                 `protobuf:"varint,5,opt,name=raft_envelope_cutover_index,json=raftEnvelopeCutoverIndex,proto3" json:"raft_envelope_cutover_index,omitempty"`
	LatestAppliedIndex       uint64                 `protobuf:"varint,6,opt,name=latest_applied_index,json=latestAppliedIndex,proto3" json:"latest_applied_index,omitempty"`
	WriterRegistryForCaller  map[uint32]uint32      `protobuf:"bytes,7,rep,name=writer_registry_for_caller,json=writerRegistryForCaller,proto3" json:"writer_registry_for_caller,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // values MUST be <= 0xFFFF.
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SidecarStateReport) Reset() {
	*x = SidecarStateReport{}
	mi := &file_encryption_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SidecarStateReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SidecarStateReport) ProtoMessage() {}

func (x *SidecarStateReport) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SidecarStateReport.ProtoReflect.Descriptor instead.
func (*SidecarStateReport) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{2}
}

func (x *SidecarStateReport) GetWrappedDeksById() map[uint32][]byte {
	if x != nil {
		return x.WrappedDeksById
	}
	return nil
}

func (x *SidecarStateReport) GetActiveStorageId() uint32 {
	if x != nil {
		return x.ActiveStorageId
	}
	return 0
}

func (x *SidecarStateReport) GetActiveRaftId() uint32 {
	if x != nil {
		return x.ActiveRaftId
	}
	return 0
}

func (x *SidecarStateReport) GetStorageEnvelopeActive() bool {
	if x != nil {
		return x.StorageEnvelopeActive
	}
	return false
}

func (x *SidecarStateReport) GetRaftEnvelopeCutoverIndex() uint64 {
	if x != nil {
		return x.RaftEnvelopeCutoverIndex
	}
	return 0
}

func (x *SidecarStateReport) GetLatestAppliedIndex() uint64 {
	if x != nil {
		return x.LatestAppliedIndex
	}
	return 0
}

func (x *SidecarStateReport) GetWriterRegistryForCaller() map[uint32]uint32 {
	if x != nil {
		return x.WriterRegistryForCaller
	}
	return nil
}

// WriterRegistryEntry is the per-member input the leader collects
// during the §5.6 step 1a batch. The two uint32 fields cover the
// 64-bit full_node_id and the 16-bit local_epoch (carried as
// uint32; <= 0xFFFF validated at the server boundary).
type WriterRegistryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullNodeId    uint64                 `protobuf:"varint,1,opt,name=full_node_id,json=fullNodeId,proto3" json:"full_node_id,omitempty"`
	LocalEpoch    uint32                 `protobuf:"varint,2,opt,name=local_epoch,json=localEpoch,proto3" json:"local_epoch,omitempty"` // MUST be <= 0xFFFF on the wire.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriterRegistryEntry) Reset() {
	*x = WriterRegistryEntry{}
	mi := &file_encryption_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriterRegistryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriterRegistryEntry) ProtoMessage() {}

func (x *WriterRegistryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriterRegistryEntry.ProtoReflect.Descriptor instead.
func (*WriterRegistryEntry) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{3}
}

func (x *WriterRegistryEntry) GetFullNodeId() uint64 {
	if x != nil {
		return x.FullNodeId
	}
	return 0
}

func (x *WriterRegistryEntry) GetLocalEpoch() uint32 {
	if x != nil {
		return x.LocalEpoch
	}
	return 0
}

// BootstrapEncryptionRequest carries the freshly-generated wrapped
// DEKs and the writer-registry batch the leader gathered from
// every member's GetCapability response. The server validates each
// local_epoch is in range before composing the §11.3 0x04
// OpBootstrap body.
type BootstrapEncryptionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WrappedStorageDek []byte                 `protobuf:"bytes,1,opt,name=wrapped_storage_dek,json=wrappedStorageDek,proto3" json:"wrapped_storage_dek,omitempty"`
	WrappedRaftDek    []byte                 `protobuf:"bytes,2,opt,name=wrapped_raft_dek,json=wrappedRaftDek,proto3" json:"wrapped_raft_dek,omitempty"`
	StorageDekId      uint32                 `protobuf:"varint,3,opt,name=storage_dek_id,json=storageDekId,proto3" json:"storage_dek_id,omitempty"`
	RaftDekId         uint32                 `protobuf:"varint,4,opt,name=raft_dek_id,json=raftDekId,proto3" json:"raft_dek_id,omitempty"`
	WriterBatch       []*WriterRegistryEntry `protobuf:"bytes,5,rep,name=writer_batch,json=writerBatch,proto3" json:"writer_batch,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BootstrapEncryptionRequest) Reset() {
	*x = BootstrapEncryptionRequest{}
	mi := &file_encryption_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapEncryptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapEncryptionRequest) ProtoMessage() {}

func (x *BootstrapEncryptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapEncryptionRequest.ProtoReflect.Descriptor instead.
func (*BootstrapEncryptionRequest) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{4}
}

func (x *BootstrapEncryptionRequest) GetWrappedStorageDek() []byte {
	if x != nil {
		return x.WrappedStorageDek
	}
	return nil
}

func (x *BootstrapEncryptionRequest) GetWrappedRaftDek() []byte {
	if x != nil {
		return x.WrappedRaftDek
	}
	return nil
}

func (x *BootstrapEncryptionRequest) GetStorageDekId() uint32 {
	if x != nil {
		return x.StorageDekId
	}
	return 0
}

func (x *BootstrapEncryptionRequest) GetRaftDekId() uint32 {
	if x != nil {
		return x.RaftDekId
	}
	return 0
}

func (x *BootstrapEncryptionRequest) GetWriterBatch() []*WriterRegistryEntry {
	if x != nil {
		return x.WriterBatch
	}
	return nil
}

type BootstrapEncryptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppliedIndex  uint64                 `protobuf:"varint,1,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapEncryptionResponse) Reset() {
	*x = BootstrapEncryptionResponse{}
	mi := &file_encryption_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapEncryptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapEncryptionResponse) ProtoMessage() {}

func (x *BootstrapEncryptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapEncryptionResponse.ProtoReflect.Descriptor instead.
func (*BootstrapEncryptionResponse) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{5}
}

func (x *BootstrapEncryptionResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

// RotateDEKRequest proposes a §5.2 rotation as a §11.3 0x05
// OpRotation entry. purpose distinguishes the two key purposes;
// the storage rotation appends a new storage DEK and shifts
// active_storage_id, and the raft rotation does the same for raft.
type RotateDEKRequest struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Purpose            RotateDEKRequest_Purpose `protobuf:"varint,1,opt,name=purpose,proto3,enum=RotateDEKRequest_Purpose" json:"purpose,omitempty"`
	WrappedNewDek      []byte                   `protobuf:"bytes,2,opt,name=wrapped_new_dek,json=wrappedNewDek,proto3" json:"wrapped_new_dek,omitempty"`
	NewDekId           uint32                   `protobuf:"varint,3,opt,name=new_dek_id,json=newDekId,proto3" json:"new_dek_id,omitempty"`
	ProposerNodeId     uint64                   `protobuf:"varint,4,opt,name=proposer_node_id,json=proposerNodeId,proto3" json:"proposer_node_id,omitempty"`             // proposer registration payload, §5.2
	ProposerLocalEpoch uint32                   `protobuf:"varint,5,opt,name=proposer_local_epoch,json=proposerLocalEpoch,proto3" json:"proposer_local_epoch,omitempty"` // MUST be <= 0xFFFF on the wire.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RotateDEKRequest) Reset() {
	*x = RotateDEKRequest{}
	mi := &file_encryption_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDEKRequest) ProtoMessage() {}

func (x *RotateDEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDEKRequest.ProtoReflect.Descriptor instead.
func (*RotateDEKRequest) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{6}
}

func (x *RotateDEKRequest) GetPurpose() RotateDEKRequest_Purpose {
	if x != nil {
		return x.Purpose
	}
	return RotateDEKRequest_PURPOSE_UNSPECIFIED
}

func (x *RotateDEKRequest) GetWrappedNewDek() []byte {
	if x != nil {
		return x.WrappedNewDek
	}
	return nil
}

func (x *RotateDEKRequest) GetNewDekId() uint32 {
	if x != nil {
		return x.NewDekId
	}
	return 0
}

func (x *RotateDEKRequest) GetProposerNodeId() uint64 {
	if x != nil {
		return x.ProposerNodeId
	}
	return 0
}

func (x *RotateDEKRequest) GetProposerLocalEpoch() uint32 {
	if x != nil {
		return x.ProposerLocalEpoch
	}
	return 0
}

type RotateDEKResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppliedIndex  uint64                 `protobuf:"varint,1,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateDEKResponse) Reset() {
	*x = RotateDEKResponse{}
	mi := &file_encryption_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDEKResponse) ProtoMessage() {}

func (x *RotateDEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDEKResponse.ProtoReflect.Descriptor instead.
func (*RotateDEKResponse) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{7}
}

func (x *RotateDEKResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

// RegisterEncryptionWriterRequest proposes a §11.3 0x03
// OpRegistration entry for the calling node. Used by nodes that
// joined the cluster after bootstrap (§5.6 step 4).
type RegisterEncryptionWriterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DekId         uint32                 `protobuf:"varint,1,opt,name=dek_id,json=dekId,proto3" json:"dek_id,omitempty"`
	Writers       []*WriterRegistryEntry `protobuf:"bytes,2,rep,name=writers,proto3" json:"writers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEncryptionWriterRequest) Reset() {
	*x = RegisterEncryptionWriterRequest{}
	mi := &file_encryption_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEncryptionWriterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEncryptionWriterRequest) ProtoMessage() {}

func (x *RegisterEncryptionWriterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEncryptionWriterRequest.ProtoReflect.Descriptor instead.
func (*RegisterEncryptionWriterRequest) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterEncryptionWriterRequest) GetDekId() uint32 {
	if x != nil {
		return x.DekId
	}
	return 0
}

func (x *RegisterEncryptionWriterRequest) GetWriters() []*WriterRegistryEntry {
	if x != nil {
		return x.Writers
	}
	return nil
}

type RegisterEncryptionWriterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppliedIndex  uint64                 `protobuf:"varint,1,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEncryptionWriterResponse) Reset() {
	*x = RegisterEncryptionWriterResponse{}
	mi := &file_encryption_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEncryptionWriterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEncryptionWriterResponse) ProtoMessage() {}

func (x *RegisterEncryptionWriterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEncryptionWriterResponse.ProtoReflect.Descriptor instead.
func (*RegisterEncryptionWriterResponse) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterEncryptionWriterResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

// ResyncSidecarRequest is the §5.5 follower-repair RPC. The caller
// asks the leader to ship its current wrapped DEK set so the
// follower can rewrite its sidecar. Read-only on the leader (no
// Raft proposal is involved).
type ResyncSidecarRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CallerFullNodeId uint64                 `protobuf:"varint,1,opt,name=caller_full_node_id,json=callerFullNodeId,proto3" json:"caller_full_node_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResyncSidecarRequest) Reset() {
	*x = ResyncSidecarRequest{}
	mi := &file_encryption_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResyncSidecarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResyncSidecarRequest) ProtoMessage() {}

func (x *ResyncSidecarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResyncSidecarRequest.ProtoReflect.Descriptor instead.
func (*ResyncSidecarRequest) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ResyncSidecarRequest) GetCallerFullNodeId() uint64 {
	if x != nil {
		return x.CallerFullNodeId
	}
	return 0
}

type ResyncSidecarResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	WrappedDeksById          map[uint32][]byte      `protobuf:"bytes,1,rep,name=wrapped_deks_by_id,json=wrappedDeksById,proto3" json:"wrapped_deks_by_id,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ActiveStorageId          uint32                 `protobuf:"varint,2,opt,name=active_storage_id,json=activeStorageId,proto3" json:"active_storage_id,omitempty"`
	ActiveRaftId             uint32                 `protobuf:"varint,3,opt,name=active_raft_id,json=activeRaftId,proto3" json:"active_raft_id,omitempty"`
	LeaderLatestAppliedIndex uint64                 `protobuf:"varint,4,opt,name=leader_latest_applied_index,json=leaderLatestAppliedIndex,proto3" json:"leader_latest_applied_index,omitempty"`
	// writer_registry_for_caller carries the leader's recorded
	// (dek_id, last_seen_local_epoch) for the calling node so the
	// follower can re-derive its §4.1 local_epoch monotonically.
	// Values MUST be <= 0xFFFF and the decode site MUST enforce
	// that bound. Empty until Stage 7 wires the registry; the
	// §5.5 recovery flow tolerates an empty map because a node
	// recovering before any DEK exists has nothing to re-derive.
	WriterRegistryForCaller map[uint32]uint32 `protobuf:"bytes,5,rep,name=writer_registry_for_caller,json=writerRegistryForCaller,proto3" json:"writer_registry_for_caller,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResyncSidecarResponse) Reset() {
	*x = ResyncSidecarResponse{}
	mi := &file_encryption_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResyncSidecarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResyncSidecarResponse) ProtoMessage() {}

func (x *ResyncSidecarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_encryption_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResyncSidecarResponse.ProtoReflect.Descriptor instead.
func (*ResyncSidecarResponse) Descriptor() ([]byte, []int) {
	return file_encryption_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ResyncSidecarResponse) GetWrappedDeksById() map[uint32][]byte {
	if x != nil {
		return x.WrappedDeksById
	}
	return nil
}

func (x *ResyncSidecarResponse) GetActiveStorageId() uint32 {
	if x != nil {
		return x.ActiveStorageId
	}
	return 0
}

func (x *ResyncSidecarResponse) GetActiveRaftId() uint32 {
	if x != nil {
		return x.ActiveRaftId
	}
	return 0
}

func (x *ResyncSidecarResponse) GetLeaderLatestAppliedIndex() uint64 {
	if x != nil {
		return x.LeaderLatestAppliedIndex
	}
	return 0
}

func (x *ResyncSidecarResponse) GetWriterRegistryForCaller() map[uint32]uint32 {
	if x != nil {
		return x.WriterRegistryForCaller
	}
	return nil
}

var File_encryption_admin_proto protoreflect.FileDescriptor

const file_encryption_admin_proto_rawDesc = "" +
	"\n" +
	"\x16encryption_admin.proto\"\a\n" +
	"\x05Empty\"\xca\x01\n" +
	"\x10CapabilityReport\x12-\n" +
	"\x12encryption_capable\x18\x01 \x01(\bR\x11encryptionCapable\x12\x1b\n" +
	"\tbuild_sha\x18\x02 \x01(\tR\bbuildSha\x12'\n" +
	"\x0fsidecar_present\x18\x03 \x01(\bR\x0esidecarPresent\x12 \n" +
	"\ffull_node_id\x18\x04 \x01(\x04R\n" +
	"fullNodeId\x12\x1f\n" +
	"\vlocal_epoch\x18\x05 \x01(\rR\n" +
	"localEpoch\"\xe5\x04\n" +
	"\x12SidecarStateReport\x12U\n" +
	"\x12wrapped_deks_by_id\x18\x01 \x03(\v2(.SidecarStateReport.WrappedDeksByIdEntryR\x0fwrappedDeksById\x12*\n" +
	"\x11active_storage_id\x18\x02 \x01(\rR\x0factiveStorageId\x12$\n" +
	"\x0eactive_raft_id\x18\x03 \x01(\rR\factiveRaftId\x126\n" +
	"\x17storage_envelope_active\x18\x04 \x01(\bR\x15storageEnvelopeActive\x12=\n" +
	"\x1braft_envelope_cutover_index\x18\x05 \x01(\x04R\x18raftEnvelopeCutoverIndex\x120\n" +
	"\x14latest_applied_index\x18\x06 \x01(\x04R\x12latestAppliedIndex\x12m\n" +
	"\x1awriter_registry_for_caller\x18\a \x03(\v20.SidecarStateReport.WriterRegistryForCallerEntryR\x17writerRegistryForCaller\x1aB\n" +
	"\x14WrappedDeksByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aJ\n" +
	"\x1cWriterRegistryForCallerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"X\n" +
	"\x13WriterRegistryEntry\x12 \n" +
	"\ffull_node_id\x18\x01 \x01(\x04R\n" +
	"fullNodeId\x12\x1f\n" +
	"\vlocal_epoch\x18\x02 \x01(\rR\n" +
	"localEpoch\"\xf5\x01\n" +
	"\x1aBootstrapEncryptionRequest\x12.\n" +
	"\x13wrapped_storage_dek\x18\x01 \x01(\fR\x11wrappedStorageDek\x12(\n" +
	"\x10wrapped_raft_dek\x18\x02 \x01(\fR\x0ewrappedRaftDek\x12$\n" +
	"\x0estorage_dek_id\x18\x03 \x01(\rR\fstorageDekId\x12\x1e\n" +
	"\vraft_dek_id\x18\x04 \x01(\rR\traftDekId\x127\n" +
	"\fwriter_batch\x18\x05 \x03(\v2\x14.WriterRegistryEntryR\vwriterBatch\"B\n" +
	"\x1bBootstrapEncryptionResponse\x12#\n" +
	"\rapplied_index\x18\x01 \x01(\x04R\fappliedIndex\"\xb4\x02\n" +
	"\x10RotateDEKRequest\x123\n" +
	"\apurpose\x18\x01 \x01(\x0e2\x19.RotateDEKRequest.PurposeR\apurpose\x12&\n" +
	"\x0fwrapped_new_dek\x18\x02 \x01(\fR\rwrappedNewDek\x12\x1c\n" +
	"\n" +
	"new_dek_id\x18\x03 \x01(\rR\bnewDekId\x12(\n" +
	"\x10proposer_node_id\x18\x04 \x01(\x04R\x0eproposerNodeId\x120\n" +
	"\x14proposer_local_epoch\x18\x05 \x01(\rR\x12proposerLocalEpoch\"I\n" +
	"\aPurpose\x12\x17\n" +
	"\x13PURPOSE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPURPOSE_STORAGE\x10\x01\x12\x10\n" +
	"\fPURPOSE_RAFT\x10\x02\"8\n" +
	"\x11RotateDEKResponse\x12#\n" +
	"\rapplied_index\x18\x01 \x01(\x04R\fappliedIndex\"h\n" +
	"\x1fRegisterEncryptionWriterRequest\x12\x15\n" +
	"\x06dek_id\x18\x01 \x01(\rR\x05dekId\x12.\n" +
	"\awriters\x18\x02 \x03(\v2\x14.WriterRegistryEntryR\awriters\"G\n" +
	" RegisterEncryptionWriterResponse\x12#\n" +
	"\rapplied_index\x18\x01 \x01(\x04R\fappliedIndex\"E\n" +
	"\x14ResyncSidecarRequest\x12-\n" +
	"\x13caller_full_node_id\x18\x01 \x01(\x04R\x10callerFullNodeId\"\x84\x04\n" +
	"\x15ResyncSidecarResponse\x12X\n" +
	"\x12wrapped_deks_by_id\x18\x01 \x03(\v2+.ResyncSidecarResponse.WrappedDeksByIdEntryR\x0fwrappedDeksById\x12*\n" +
	"\x11active_storage_id\x18\x02 \x01(\rR\x0factiveStorageId\x12$\n" +
	"\x0eactive_raft_id\x18\x03 \x01(\rR\factiveRaftId\x12=\n" +
	"\x1bleader_latest_applied_index\x18\x04 \x01(\x04R\x18leaderLatestAppliedIndex\x12p\n" +
	"\x1awriter_registry_for_caller\x18\x05 \x03(\v23.ResyncSidecarResponse.WriterRegistryForCallerEntryR\x17writerRegistryForCaller\x1aB\n" +
	"\x14WrappedDeksByIdEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aJ\n" +
	"\x1cWriterRegistryForCallerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x012\xa0\x03\n" +
	"\x0fEncryptionAdmin\x12,\n" +
	"\rGetCapability\x12\x06.Empty\x1a\x11.CapabilityReport\"\x00\x120\n" +
	"\x0fGetSidecarState\x12\x06.Empty\x1a\x13.SidecarStateReport\"\x00\x12R\n" +
	"\x13BootstrapEncryption\x12\x1b.BootstrapEncryptionRequest\x1a\x1c.BootstrapEncryptionResponse\"\x00\x124\n" +
	"\tRotateDEK\x12\x11.RotateDEKRequest\x1a\x12.RotateDEKResponse\"\x00\x12a\n" +
	"\x18RegisterEncryptionWriter\x12 .RegisterEncryptionWriterRequest\x1a!.RegisterEncryptionWriterResponse\"\x00\x12@\n" +
	"\rResyncSidecar\x12\x15.ResyncSidecarRequest\x1a\x16.ResyncSidecarResponse\"\x00B#Z!github.com/bootjp/elastickv/protob\x06proto3"

var (
	file_encryption_admin_proto_rawDescOnce sync.Once
	file_encryption_admin_proto_rawDescData []byte
)

func file_encryption_admin_proto_rawDescGZIP() []byte {
	file_encryption_admin_proto_rawDescOnce.Do(func() {
		file_encryption_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_encryption_admin_proto_rawDesc), len(file_encryption_admin_proto_rawDesc)))
	})
	return file_encryption_admin_proto_rawDescData
}

var file_encryption_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_encryption_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_encryption_admin_proto_goTypes = []any{
	(RotateDEKRequest_Purpose)(0),            // 0: RotateDEKRequest.Purpose
	(*Empty)(nil),                            // 1: Empty
	(*CapabilityReport)(nil),                 // 2: CapabilityReport
	(*SidecarStateReport)(nil),               // 3: SidecarStateReport
	(*WriterRegistryEntry)(nil),              // 4: WriterRegistryEntry
	(*BootstrapEncryptionRequest)(nil),       // 5: BootstrapEncryptionRequest
	(*BootstrapEncryptionResponse)(nil),      // 6: BootstrapEncryptionResponse
	(*RotateDEKRequest)(nil),                 // 7: RotateDEKRequest
	(*RotateDEKResponse)(nil),                // 8: RotateDEKResponse
	(*RegisterEncryptionWriterRequest)(nil),  // 9: RegisterEncryptionWriterRequest
	(*RegisterEncryptionWriterResponse)(nil), // 10: RegisterEncryptionWriterResponse
	(*ResyncSidecarRequest)(nil),             // 11: ResyncSidecarRequest
	(*ResyncSidecarResponse)(nil),            // 12: ResyncSidecarResponse
	nil,                                      // 13: SidecarStateReport.WrappedDeksByIdEntry
	nil,                                      // 14: SidecarStateReport.WriterRegistryForCallerEntry
	nil,                                      // 15: ResyncSidecarResponse.WrappedDeksByIdEntry
	nil,                                      // 16: ResyncSidecarResponse.WriterRegistryForCallerEntry
}
var file_encryption_admin_proto_depIdxs = []int32{
	13, // 0: SidecarStateReport.wrapped_deks_by_id:type_name -> SidecarStateReport.WrappedDeksByIdEntry
	14, // 1: SidecarStateReport.writer_registry_for_caller:type_name -> SidecarStateReport.WriterRegistryForCallerEntry
	4,  // 2: BootstrapEncryptionRequest.writer_batch:type_name -> WriterRegistryEntry
	0,  // 3: RotateDEKRequest.purpose:type_name -> RotateDEKRequest.Purpose
	4,  // 4: RegisterEncryptionWriterRequest.writers:type_name -> WriterRegistryEntry
	15, // 5: ResyncSidecarResponse.wrapped_deks_by_id:type_name -> ResyncSidecarResponse.WrappedDeksByIdEntry
	16, // 6: ResyncSidecarResponse.writer_registry_for_caller:type_name -> ResyncSidecarResponse.WriterRegistryForCallerEntry
	1,  // 7: EncryptionAdmin.GetCapability:input_type -> Empty
	1,  // 8: EncryptionAdmin.GetSidecarState:input_type -> Empty
	5,  // 9: EncryptionAdmin.BootstrapEncryption:input_type -> BootstrapEncryptionRequest
	7,  // 10: EncryptionAdmin.RotateDEK:input_type -> RotateDEKRequest
	9,  // 11: EncryptionAdmin.RegisterEncryptionWriter:input_type -> RegisterEncryptionWriterRequest
	11, // 12: EncryptionAdmin.ResyncSidecar:input_type -> ResyncSidecarRequest
	2,  // 13: EncryptionAdmin.GetCapability:output_type -> CapabilityReport
	3,  // 14: EncryptionAdmin.GetSidecarState:output_type -> SidecarStateReport
	6,  // 15: EncryptionAdmin.BootstrapEncryption:output_type -> BootstrapEncryptionResponse
	8,  // 16: EncryptionAdmin.RotateDEK:output_type -> RotateDEKResponse
	10, // 17: EncryptionAdmin.RegisterEncryptionWriter:output_type -> RegisterEncryptionWriterResponse
	12, // 18: EncryptionAdmin.ResyncSidecar:output_type -> ResyncSidecarResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_encryption_admin_proto_init() }
func file_encryption_admin_proto_init() {
	if File_encryption_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_encryption_admin_proto_rawDesc), len(file_encryption_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encryption_admin_proto_goTypes,
		DependencyIndexes: file_encryption_admin_proto_depIdxs,
		EnumInfos:         file_encryption_admin_proto_enumTypes,
		MessageInfos:      file_encryption_admin_proto_msgTypes,
	}.Build()
	File_encryption_admin_proto = out.File
	file_encryption_admin_proto_goTypes = nil
	file_encryption_admin_proto_depIdxs = nil
}
