// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.6
// source: encryption_admin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EncryptionAdmin_GetCapability_FullMethodName            = "/EncryptionAdmin/GetCapability"
	EncryptionAdmin_GetSidecarState_FullMethodName          = "/EncryptionAdmin/GetSidecarState"
	EncryptionAdmin_BootstrapEncryption_FullMethodName      = "/EncryptionAdmin/BootstrapEncryption"
	EncryptionAdmin_RotateDEK_FullMethodName                = "/EncryptionAdmin/RotateDEK"
	EncryptionAdmin_RegisterEncryptionWriter_FullMethodName = "/EncryptionAdmin/RegisterEncryptionWriter"
	EncryptionAdmin_ResyncSidecar_FullMethodName            = "/EncryptionAdmin/ResyncSidecar"
	EncryptionAdmin_EnableStorageEnvelope_FullMethodName    = "/EncryptionAdmin/EnableStorageEnvelope"
)

// EncryptionAdminClient is the client API for EncryptionAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EncryptionAdmin is the operator-facing control plane for the
// data-at-rest encryption feature described in
// docs/design/2026_04_29_partial_data_at_rest_encryption.md. The
// service is split into two groups:
//
//  1. Read-only, leaderless probes (GetCapability,
//     GetSidecarState, ResyncSidecar). Safe to call on any
//     member including learners; each returns the responding
//     node's local view. The §5.6 / §7.1 cutover paths fan
//     GetCapability out across every member of every Raft group
//     to drive the pre-flight capability check and to collect
//     the (full_node_id, local_epoch) batch that goes into the
//     bootstrap-encryption Raft entry. GetSidecarState and
//     ResyncSidecar share the §5.5 sidecar-recovery role: a
//     follower whose sidecar fell behind a Raft-log compaction
//     window calls either RPC against the leader and rewrites
//     its local keys.json from the response. ResyncSidecar is
//     addressed at the leader because the recovery flow only
//     consults the leader's record; GetSidecarState answers from
//     any node and is the broader observability surface.
//
//  2. Mutating RPCs that propose FSM-internal entries through
//     the default Raft group's leader (BootstrapEncryption,
//     RotateDEK, RegisterEncryptionWriter). They route to the
//     leader; followers return FailedPrecondition with the
//     currently-known leader so the operator's CLI can retry
//     against the right node.
//
// Wire-format notes:
//   - local_epoch is the §4.1 16-bit nonce field carried as
//     uint32 (proto3 has no uint16). Every decode site MUST
//     validate value <= 0xFFFF; values above 0xFFFF return
//     ErrLocalEpochOutOfRange. The mutating RPCs that accept a
//     writer-registry batch (BootstrapEncryption) MUST apply the
//     same check at the server boundary before the batch is
//     forwarded into the Raft proposal.
//   - wrapped_dek payloads are sidecar-format bytes (DEK wrapped
//     under the current KEK) and are leakage-safe: an RPC
//     response that exposes them is no worse than reading the
//     on-disk sidecar.
type EncryptionAdminClient interface {
	GetCapability(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityReport, error)
	GetSidecarState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SidecarStateReport, error)
	BootstrapEncryption(ctx context.Context, in *BootstrapEncryptionRequest, opts ...grpc.CallOption) (*BootstrapEncryptionResponse, error)
	RotateDEK(ctx context.Context, in *RotateDEKRequest, opts ...grpc.CallOption) (*RotateDEKResponse, error)
	RegisterEncryptionWriter(ctx context.Context, in *RegisterEncryptionWriterRequest, opts ...grpc.CallOption) (*RegisterEncryptionWriterResponse, error)
	ResyncSidecar(ctx context.Context, in *ResyncSidecarRequest, opts ...grpc.CallOption) (*ResyncSidecarResponse, error)
	EnableStorageEnvelope(ctx context.Context, in *EnableStorageEnvelopeRequest, opts ...grpc.CallOption) (*EnableStorageEnvelopeResponse, error)
}

type encryptionAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewEncryptionAdminClient(cc grpc.ClientConnInterface) EncryptionAdminClient {
	return &encryptionAdminClient{cc}
}

func (c *encryptionAdminClient) GetCapability(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CapabilityReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilityReport)
	err := c.cc.Invoke(ctx, EncryptionAdmin_GetCapability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionAdminClient) GetSidecarState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SidecarStateReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SidecarStateReport)
	err := c.cc.Invoke(ctx, EncryptionAdmin_GetSidecarState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionAdminClient) BootstrapEncryption(ctx context.Context, in *BootstrapEncryptionRequest, opts ...grpc.CallOption) (*BootstrapEncryptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapEncryptionResponse)
	err := c.cc.Invoke(ctx, EncryptionAdmin_BootstrapEncryption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionAdminClient) RotateDEK(ctx context.Context, in *RotateDEKRequest, opts ...grpc.CallOption) (*RotateDEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateDEKResponse)
	err := c.cc.Invoke(ctx, EncryptionAdmin_RotateDEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionAdminClient) RegisterEncryptionWriter(ctx context.Context, in *RegisterEncryptionWriterRequest, opts ...grpc.CallOption) (*RegisterEncryptionWriterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterEncryptionWriterResponse)
	err := c.cc.Invoke(ctx, EncryptionAdmin_RegisterEncryptionWriter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionAdminClient) ResyncSidecar(ctx context.Context, in *ResyncSidecarRequest, opts ...grpc.CallOption) (*ResyncSidecarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResyncSidecarResponse)
	err := c.cc.Invoke(ctx, EncryptionAdmin_ResyncSidecar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *encryptionAdminClient) EnableStorageEnvelope(ctx context.Context, in *EnableStorageEnvelopeRequest, opts ...grpc.CallOption) (*EnableStorageEnvelopeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableStorageEnvelopeResponse)
	err := c.cc.Invoke(ctx, EncryptionAdmin_EnableStorageEnvelope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EncryptionAdminServer is the server API for EncryptionAdmin service.
// All implementations must embed UnimplementedEncryptionAdminServer
// for forward compatibility.
//
// EncryptionAdmin is the operator-facing control plane for the
// data-at-rest encryption feature described in
// docs/design/2026_04_29_partial_data_at_rest_encryption.md. The
// service is split into two groups:
//
//  1. Read-only, leaderless probes (GetCapability,
//     GetSidecarState, ResyncSidecar). Safe to call on any
//     member including learners; each returns the responding
//     node's local view. The §5.6 / §7.1 cutover paths fan
//     GetCapability out across every member of every Raft group
//     to drive the pre-flight capability check and to collect
//     the (full_node_id, local_epoch) batch that goes into the
//     bootstrap-encryption Raft entry. GetSidecarState and
//     ResyncSidecar share the §5.5 sidecar-recovery role: a
//     follower whose sidecar fell behind a Raft-log compaction
//     window calls either RPC against the leader and rewrites
//     its local keys.json from the response. ResyncSidecar is
//     addressed at the leader because the recovery flow only
//     consults the leader's record; GetSidecarState answers from
//     any node and is the broader observability surface.
//
//  2. Mutating RPCs that propose FSM-internal entries through
//     the default Raft group's leader (BootstrapEncryption,
//     RotateDEK, RegisterEncryptionWriter). They route to the
//     leader; followers return FailedPrecondition with the
//     currently-known leader so the operator's CLI can retry
//     against the right node.
//
// Wire-format notes:
//   - local_epoch is the §4.1 16-bit nonce field carried as
//     uint32 (proto3 has no uint16). Every decode site MUST
//     validate value <= 0xFFFF; values above 0xFFFF return
//     ErrLocalEpochOutOfRange. The mutating RPCs that accept a
//     writer-registry batch (BootstrapEncryption) MUST apply the
//     same check at the server boundary before the batch is
//     forwarded into the Raft proposal.
//   - wrapped_dek payloads are sidecar-format bytes (DEK wrapped
//     under the current KEK) and are leakage-safe: an RPC
//     response that exposes them is no worse than reading the
//     on-disk sidecar.
type EncryptionAdminServer interface {
	GetCapability(context.Context, *Empty) (*CapabilityReport, error)
	GetSidecarState(context.Context, *Empty) (*SidecarStateReport, error)
	BootstrapEncryption(context.Context, *BootstrapEncryptionRequest) (*BootstrapEncryptionResponse, error)
	RotateDEK(context.Context, *RotateDEKRequest) (*RotateDEKResponse, error)
	RegisterEncryptionWriter(context.Context, *RegisterEncryptionWriterRequest) (*RegisterEncryptionWriterResponse, error)
	ResyncSidecar(context.Context, *ResyncSidecarRequest) (*ResyncSidecarResponse, error)
	EnableStorageEnvelope(context.Context, *EnableStorageEnvelopeRequest) (*EnableStorageEnvelopeResponse, error)
	mustEmbedUnimplementedEncryptionAdminServer()
}

// UnimplementedEncryptionAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEncryptionAdminServer struct{}

func (UnimplementedEncryptionAdminServer) GetCapability(context.Context, *Empty) (*CapabilityReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapability not implemented")
}
func (UnimplementedEncryptionAdminServer) GetSidecarState(context.Context, *Empty) (*SidecarStateReport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSidecarState not implemented")
}
func (UnimplementedEncryptionAdminServer) BootstrapEncryption(context.Context, *BootstrapEncryptionRequest) (*BootstrapEncryptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BootstrapEncryption not implemented")
}
func (UnimplementedEncryptionAdminServer) RotateDEK(context.Context, *RotateDEKRequest) (*RotateDEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateDEK not implemented")
}
func (UnimplementedEncryptionAdminServer) RegisterEncryptionWriter(context.Context, *RegisterEncryptionWriterRequest) (*RegisterEncryptionWriterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterEncryptionWriter not implemented")
}
func (UnimplementedEncryptionAdminServer) ResyncSidecar(context.Context, *ResyncSidecarRequest) (*ResyncSidecarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResyncSidecar not implemented")
}
func (UnimplementedEncryptionAdminServer) EnableStorageEnvelope(context.Context, *EnableStorageEnvelopeRequest) (*EnableStorageEnvelopeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableStorageEnvelope not implemented")
}
func (UnimplementedEncryptionAdminServer) mustEmbedUnimplementedEncryptionAdminServer() {}
func (UnimplementedEncryptionAdminServer) testEmbeddedByValue()                         {}

// UnsafeEncryptionAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EncryptionAdminServer will
// result in compilation errors.
type UnsafeEncryptionAdminServer interface {
	mustEmbedUnimplementedEncryptionAdminServer()
}

func RegisterEncryptionAdminServer(s grpc.ServiceRegistrar, srv EncryptionAdminServer) {
	// If the following call panics, it indicates UnimplementedEncryptionAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EncryptionAdmin_ServiceDesc, srv)
}

func _EncryptionAdmin_GetCapability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionAdminServer).GetCapability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionAdmin_GetCapability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionAdminServer).GetCapability(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionAdmin_GetSidecarState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionAdminServer).GetSidecarState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionAdmin_GetSidecarState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionAdminServer).GetSidecarState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionAdmin_BootstrapEncryption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapEncryptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionAdminServer).BootstrapEncryption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionAdmin_BootstrapEncryption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionAdminServer).BootstrapEncryption(ctx, req.(*BootstrapEncryptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionAdmin_RotateDEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateDEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionAdminServer).RotateDEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionAdmin_RotateDEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionAdminServer).RotateDEK(ctx, req.(*RotateDEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionAdmin_RegisterEncryptionWriter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterEncryptionWriterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionAdminServer).RegisterEncryptionWriter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionAdmin_RegisterEncryptionWriter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionAdminServer).RegisterEncryptionWriter(ctx, req.(*RegisterEncryptionWriterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionAdmin_ResyncSidecar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResyncSidecarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionAdminServer).ResyncSidecar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionAdmin_ResyncSidecar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionAdminServer).ResyncSidecar(ctx, req.(*ResyncSidecarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EncryptionAdmin_EnableStorageEnvelope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableStorageEnvelopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptionAdminServer).EnableStorageEnvelope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EncryptionAdmin_EnableStorageEnvelope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptionAdminServer).EnableStorageEnvelope(ctx, req.(*EnableStorageEnvelopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EncryptionAdmin_ServiceDesc is the grpc.ServiceDesc for EncryptionAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EncryptionAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EncryptionAdmin",
	HandlerType: (*EncryptionAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapability",
			Handler:    _EncryptionAdmin_GetCapability_Handler,
		},
		{
			MethodName: "GetSidecarState",
			Handler:    _EncryptionAdmin_GetSidecarState_Handler,
		},
		{
			MethodName: "BootstrapEncryption",
			Handler:    _EncryptionAdmin_BootstrapEncryption_Handler,
		},
		{
			MethodName: "RotateDEK",
			Handler:    _EncryptionAdmin_RotateDEK_Handler,
		},
		{
			MethodName: "RegisterEncryptionWriter",
			Handler:    _EncryptionAdmin_RegisterEncryptionWriter_Handler,
		},
		{
			MethodName: "ResyncSidecar",
			Handler:    _EncryptionAdmin_ResyncSidecar_Handler,
		},
		{
			MethodName: "EnableStorageEnvelope",
			Handler:    _EncryptionAdmin_EnableStorageEnvelope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "encryption_admin.proto",
}
