// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: etcd_raft.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EtcdRaft_Send_FullMethodName         = "/EtcdRaft/Send"
	EtcdRaft_SendSnapshot_FullMethodName = "/EtcdRaft/SendSnapshot"
)

// EtcdRaftClient is the client API for EtcdRaft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EtcdRaftClient interface {
	Send(ctx context.Context, in *EtcdRaftMessage, opts ...grpc.CallOption) (*EtcdRaftAck, error)
	SendSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EtcdRaftSnapshotChunk, EtcdRaftAck], error)
}

type etcdRaftClient struct {
	cc grpc.ClientConnInterface
}

func NewEtcdRaftClient(cc grpc.ClientConnInterface) EtcdRaftClient {
	return &etcdRaftClient{cc}
}

func (c *etcdRaftClient) Send(ctx context.Context, in *EtcdRaftMessage, opts ...grpc.CallOption) (*EtcdRaftAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EtcdRaftAck)
	err := c.cc.Invoke(ctx, EtcdRaft_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdRaftClient) SendSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EtcdRaftSnapshotChunk, EtcdRaftAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EtcdRaft_ServiceDesc.Streams[0], EtcdRaft_SendSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EtcdRaftSnapshotChunk, EtcdRaftAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EtcdRaft_SendSnapshotClient = grpc.ClientStreamingClient[EtcdRaftSnapshotChunk, EtcdRaftAck]

// EtcdRaftServer is the server API for EtcdRaft service.
// All implementations must embed UnimplementedEtcdRaftServer
// for forward compatibility.
type EtcdRaftServer interface {
	Send(context.Context, *EtcdRaftMessage) (*EtcdRaftAck, error)
	SendSnapshot(grpc.ClientStreamingServer[EtcdRaftSnapshotChunk, EtcdRaftAck]) error
	mustEmbedUnimplementedEtcdRaftServer()
}

// UnimplementedEtcdRaftServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEtcdRaftServer struct{}

func (UnimplementedEtcdRaftServer) Send(context.Context, *EtcdRaftMessage) (*EtcdRaftAck, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedEtcdRaftServer) SendSnapshot(grpc.ClientStreamingServer[EtcdRaftSnapshotChunk, EtcdRaftAck]) error {
	return status.Error(codes.Unimplemented, "method SendSnapshot not implemented")
}
func (UnimplementedEtcdRaftServer) mustEmbedUnimplementedEtcdRaftServer() {}
func (UnimplementedEtcdRaftServer) testEmbeddedByValue()                  {}

// UnsafeEtcdRaftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EtcdRaftServer will
// result in compilation errors.
type UnsafeEtcdRaftServer interface {
	mustEmbedUnimplementedEtcdRaftServer()
}

func RegisterEtcdRaftServer(s grpc.ServiceRegistrar, srv EtcdRaftServer) {
	// If the following call panics, it indicates UnimplementedEtcdRaftServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EtcdRaft_ServiceDesc, srv)
}

func _EtcdRaft_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EtcdRaftMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdRaftServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdRaft_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdRaftServer).Send(ctx, req.(*EtcdRaftMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdRaft_SendSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EtcdRaftServer).SendSnapshot(&grpc.GenericServerStream[EtcdRaftSnapshotChunk, EtcdRaftAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EtcdRaft_SendSnapshotServer = grpc.ClientStreamingServer[EtcdRaftSnapshotChunk, EtcdRaftAck]

// EtcdRaft_ServiceDesc is the grpc.ServiceDesc for EtcdRaft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EtcdRaft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EtcdRaft",
	HandlerType: (*EtcdRaftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _EtcdRaft_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendSnapshot",
			Handler:       _EtcdRaft_SendSnapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "etcd_raft.proto",
}
