// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: redis_internal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedisHashValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       map[string]string      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisHashValue) Reset() {
	*x = RedisHashValue{}
	mi := &file_redis_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisHashValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisHashValue) ProtoMessage() {}

func (x *RedisHashValue) ProtoReflect() protoreflect.Message {
	mi := &file_redis_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisHashValue.ProtoReflect.Descriptor instead.
func (*RedisHashValue) Descriptor() ([]byte, []int) {
	return file_redis_internal_proto_rawDescGZIP(), []int{0}
}

func (x *RedisHashValue) GetEntries() map[string]string {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RedisSetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []string               `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisSetValue) Reset() {
	*x = RedisSetValue{}
	mi := &file_redis_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisSetValue) ProtoMessage() {}

func (x *RedisSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_redis_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisSetValue.ProtoReflect.Descriptor instead.
func (*RedisSetValue) Descriptor() ([]byte, []int) {
	return file_redis_internal_proto_rawDescGZIP(), []int{1}
}

func (x *RedisSetValue) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type RedisZSetEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisZSetEntry) Reset() {
	*x = RedisZSetEntry{}
	mi := &file_redis_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisZSetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisZSetEntry) ProtoMessage() {}

func (x *RedisZSetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_redis_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisZSetEntry.ProtoReflect.Descriptor instead.
func (*RedisZSetEntry) Descriptor() ([]byte, []int) {
	return file_redis_internal_proto_rawDescGZIP(), []int{2}
}

func (x *RedisZSetEntry) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *RedisZSetEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type RedisZSetValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RedisZSetEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisZSetValue) Reset() {
	*x = RedisZSetValue{}
	mi := &file_redis_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisZSetValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisZSetValue) ProtoMessage() {}

func (x *RedisZSetValue) ProtoReflect() protoreflect.Message {
	mi := &file_redis_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisZSetValue.ProtoReflect.Descriptor instead.
func (*RedisZSetValue) Descriptor() ([]byte, []int) {
	return file_redis_internal_proto_rawDescGZIP(), []int{3}
}

func (x *RedisZSetValue) GetEntries() []*RedisZSetEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RedisStreamEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisStreamEntry) Reset() {
	*x = RedisStreamEntry{}
	mi := &file_redis_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisStreamEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisStreamEntry) ProtoMessage() {}

func (x *RedisStreamEntry) ProtoReflect() protoreflect.Message {
	mi := &file_redis_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisStreamEntry.ProtoReflect.Descriptor instead.
func (*RedisStreamEntry) Descriptor() ([]byte, []int) {
	return file_redis_internal_proto_rawDescGZIP(), []int{4}
}

func (x *RedisStreamEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RedisStreamEntry) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RedisStreamValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RedisStreamEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisStreamValue) Reset() {
	*x = RedisStreamValue{}
	mi := &file_redis_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisStreamValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisStreamValue) ProtoMessage() {}

func (x *RedisStreamValue) ProtoReflect() protoreflect.Message {
	mi := &file_redis_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisStreamValue.ProtoReflect.Descriptor instead.
func (*RedisStreamValue) Descriptor() ([]byte, []int) {
	return file_redis_internal_proto_rawDescGZIP(), []int{5}
}

func (x *RedisStreamValue) GetEntries() []*RedisStreamEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_redis_internal_proto protoreflect.FileDescriptor

const file_redis_internal_proto_rawDesc = "" +
	"\n" +
	"\x14redis_internal.proto\"\x84\x01\n" +
	"\x0eRedisHashValue\x126\n" +
	"\aentries\x18\x01 \x03(\v2\x1c.RedisHashValue.EntriesEntryR\aentries\x1a:\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\rRedisSetValue\x12\x18\n" +
	"\amembers\x18\x01 \x03(\tR\amembers\">\n" +
	"\x0eRedisZSetEntry\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\";\n" +
	"\x0eRedisZSetValue\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.RedisZSetEntryR\aentries\":\n" +
	"\x10RedisStreamEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"?\n" +
	"\x10RedisStreamValue\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.RedisStreamEntryR\aentriesB#Z!github.com/bootjp/elastickv/protob\x06proto3"

var (
	file_redis_internal_proto_rawDescOnce sync.Once
	file_redis_internal_proto_rawDescData []byte
)

func file_redis_internal_proto_rawDescGZIP() []byte {
	file_redis_internal_proto_rawDescOnce.Do(func() {
		file_redis_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redis_internal_proto_rawDesc), len(file_redis_internal_proto_rawDesc)))
	})
	return file_redis_internal_proto_rawDescData
}

var file_redis_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_redis_internal_proto_goTypes = []any{
	(*RedisHashValue)(nil),   // 0: RedisHashValue
	(*RedisSetValue)(nil),    // 1: RedisSetValue
	(*RedisZSetEntry)(nil),   // 2: RedisZSetEntry
	(*RedisZSetValue)(nil),   // 3: RedisZSetValue
	(*RedisStreamEntry)(nil), // 4: RedisStreamEntry
	(*RedisStreamValue)(nil), // 5: RedisStreamValue
	nil,                      // 6: RedisHashValue.EntriesEntry
}
var file_redis_internal_proto_depIdxs = []int32{
	6, // 0: RedisHashValue.entries:type_name -> RedisHashValue.EntriesEntry
	2, // 1: RedisZSetValue.entries:type_name -> RedisZSetEntry
	4, // 2: RedisStreamValue.entries:type_name -> RedisStreamEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_redis_internal_proto_init() }
func file_redis_internal_proto_init() {
	if File_redis_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redis_internal_proto_rawDesc), len(file_redis_internal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_internal_proto_goTypes,
		DependencyIndexes: file_redis_internal_proto_depIdxs,
		MessageInfos:      file_redis_internal_proto_msgTypes,
	}.Build()
	File_redis_internal_proto = out.File
	file_redis_internal_proto_goTypes = nil
	file_redis_internal_proto_depIdxs = nil
}
