// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftAdminState int32

const (
	RaftAdminState_RAFT_ADMIN_STATE_UNKNOWN   RaftAdminState = 0
	RaftAdminState_RAFT_ADMIN_STATE_FOLLOWER  RaftAdminState = 1
	RaftAdminState_RAFT_ADMIN_STATE_CANDIDATE RaftAdminState = 2
	RaftAdminState_RAFT_ADMIN_STATE_LEADER    RaftAdminState = 3
	RaftAdminState_RAFT_ADMIN_STATE_SHUTDOWN  RaftAdminState = 4
)

// Enum value maps for RaftAdminState.
var (
	RaftAdminState_name = map[int32]string{
		0: "RAFT_ADMIN_STATE_UNKNOWN",
		1: "RAFT_ADMIN_STATE_FOLLOWER",
		2: "RAFT_ADMIN_STATE_CANDIDATE",
		3: "RAFT_ADMIN_STATE_LEADER",
		4: "RAFT_ADMIN_STATE_SHUTDOWN",
	}
	RaftAdminState_value = map[string]int32{
		"RAFT_ADMIN_STATE_UNKNOWN":   0,
		"RAFT_ADMIN_STATE_FOLLOWER":  1,
		"RAFT_ADMIN_STATE_CANDIDATE": 2,
		"RAFT_ADMIN_STATE_LEADER":    3,
		"RAFT_ADMIN_STATE_SHUTDOWN":  4,
	}
)

func (x RaftAdminState) Enum() *RaftAdminState {
	p := new(RaftAdminState)
	*p = x
	return p
}

func (x RaftAdminState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftAdminState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (RaftAdminState) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x RaftAdminState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftAdminState.Descriptor instead.
func (RaftAdminState) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type RawPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPutRequest) Reset() {
	*x = RawPutRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutRequest) ProtoMessage() {}

func (x *RawPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutRequest.ProtoReflect.Descriptor instead.
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *RawPutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawPutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RawPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitIndex   uint64                 `protobuf:"varint,1,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPutResponse) Reset() {
	*x = RawPutResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPutResponse) ProtoMessage() {}

func (x *RawPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPutResponse.ProtoReflect.Descriptor instead.
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *RawPutResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *RawPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RawGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Ts            uint64                 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"` // optional read timestamp; if zero, server uses current HLC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawGetRequest) Reset() {
	*x = RawGetRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetRequest) ProtoMessage() {}

func (x *RawGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetRequest.ProtoReflect.Descriptor instead.
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *RawGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawGetRequest) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type RawGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadAtIndex   uint64                 `protobuf:"varint,1,opt,name=read_at_index,json=readAtIndex,proto3" json:"read_at_index,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Exists        bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawGetResponse) Reset() {
	*x = RawGetResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawGetResponse) ProtoMessage() {}

func (x *RawGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawGetResponse.ProtoReflect.Descriptor instead.
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *RawGetResponse) GetReadAtIndex() uint64 {
	if x != nil {
		return x.ReadAtIndex
	}
	return 0
}

func (x *RawGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *RawGetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type RawDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawDeleteRequest) Reset() {
	*x = RawDeleteRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteRequest) ProtoMessage() {}

func (x *RawDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteRequest.ProtoReflect.Descriptor instead.
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *RawDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RawDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitIndex   uint64                 `protobuf:"varint,1,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawDeleteResponse) Reset() {
	*x = RawDeleteResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawDeleteResponse) ProtoMessage() {}

func (x *RawDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawDeleteResponse.ProtoReflect.Descriptor instead.
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *RawDeleteResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *RawDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RawLatestCommitTSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawLatestCommitTSRequest) Reset() {
	*x = RawLatestCommitTSRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawLatestCommitTSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawLatestCommitTSRequest) ProtoMessage() {}

func (x *RawLatestCommitTSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawLatestCommitTSRequest.ProtoReflect.Descriptor instead.
func (*RawLatestCommitTSRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *RawLatestCommitTSRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type RawLatestCommitTSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            uint64                 `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Exists        bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawLatestCommitTSResponse) Reset() {
	*x = RawLatestCommitTSResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawLatestCommitTSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawLatestCommitTSResponse) ProtoMessage() {}

func (x *RawLatestCommitTSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawLatestCommitTSResponse.ProtoReflect.Descriptor instead.
func (*RawLatestCommitTSResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *RawLatestCommitTSResponse) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *RawLatestCommitTSResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type RawScanAtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // validated against host int size; large values may be rejected
	Ts            uint64                 `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`       // optional read timestamp; if zero, server uses current HLC
	Reverse       bool                   `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawScanAtRequest) Reset() {
	*x = RawScanAtRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawScanAtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanAtRequest) ProtoMessage() {}

func (x *RawScanAtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanAtRequest.ProtoReflect.Descriptor instead.
func (*RawScanAtRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *RawScanAtRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RawScanAtRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *RawScanAtRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RawScanAtRequest) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *RawScanAtRequest) GetReverse() bool {
	if x != nil {
		return x.Reverse
	}
	return false
}

type RawKVPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawKVPair) Reset() {
	*x = RawKVPair{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawKVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawKVPair) ProtoMessage() {}

func (x *RawKVPair) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawKVPair.ProtoReflect.Descriptor instead.
func (*RawKVPair) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *RawKVPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *RawKVPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RawScanAtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            []*RawKVPair           `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawScanAtResponse) Reset() {
	*x = RawScanAtResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawScanAtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawScanAtResponse) ProtoMessage() {}

func (x *RawScanAtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawScanAtResponse.ProtoReflect.Descriptor instead.
func (*RawScanAtResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *RawScanAtResponse) GetKv() []*RawKVPair {
	if x != nil {
		return x.Kv
	}
	return nil
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitIndex   uint64                 `protobuf:"varint,1,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *PutResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitIndex   uint64                 `protobuf:"varint,1,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadAtIndex   uint64                 `protobuf:"varint,1,opt,name=read_at_index,json=readAtIndex,proto3" json:"read_at_index,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetResponse) GetReadAtIndex() uint64 {
	if x != nil {
		return x.ReadAtIndex
	}
	return 0
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type KeyError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyError) Reset() {
	*x = KeyError{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyError) ProtoMessage() {}

func (x *KeyError) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyError.ProtoReflect.Descriptor instead.
func (*KeyError) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *KeyError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KeyError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type Kv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *KeyError              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kv) Reset() {
	*x = Kv{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kv) ProtoMessage() {}

func (x *Kv) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kv.ProtoReflect.Descriptor instead.
func (*Kv) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *Kv) GetError() *KeyError {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Kv) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Kv) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartKey      []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	EndKey        []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey,proto3" json:"end_key,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *ScanRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *ScanRequest) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *ScanRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kv            []*Kv                  `protobuf:"bytes,1,rep,name=kv,proto3" json:"kv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *ScanResponse) GetKv() []*Kv {
	if x != nil {
		return x.Kv
	}
	return nil
}

type PreWriteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mutations is the list of mutations to apply atomically.
	Mutations []*Kv `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
	// start_ts is the timestamp of the transaction.
	StartTs uint64 `protobuf:"varint,3,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	// lock_ttl is the TTL of the lock in milliseconds.
	LockTtl       uint64 `protobuf:"varint,4,opt,name=lock_ttl,json=lockTtl,proto3" json:"lock_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreWriteRequest) Reset() {
	*x = PreWriteRequest{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreWriteRequest) ProtoMessage() {}

func (x *PreWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreWriteRequest.ProtoReflect.Descriptor instead.
func (*PreWriteRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *PreWriteRequest) GetMutations() []*Kv {
	if x != nil {
		return x.Mutations
	}
	return nil
}

func (x *PreWriteRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *PreWriteRequest) GetLockTtl() uint64 {
	if x != nil {
		return x.LockTtl
	}
	return 0
}

type PreCommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*KeyError            `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreCommitResponse) Reset() {
	*x = PreCommitResponse{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreCommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreCommitResponse) ProtoMessage() {}

func (x *PreCommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreCommitResponse.ProtoReflect.Descriptor instead.
func (*PreCommitResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *PreCommitResponse) GetErrors() []*KeyError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CommitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// start_ts is the timestamp of prewrite request.
	StartTs       uint64   `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	Keys          [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *CommitRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

func (x *CommitRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type CommitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitIndex   uint64                 `protobuf:"varint,1,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Errors        []*KeyError            `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *CommitResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *CommitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitResponse) GetErrors() []*KeyError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type RollbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTs       uint64                 `protobuf:"varint,1,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackRequest) Reset() {
	*x = RollbackRequest{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackRequest) ProtoMessage() {}

func (x *RollbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackRequest.ProtoReflect.Descriptor instead.
func (*RollbackRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *RollbackRequest) GetStartTs() uint64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

type RollbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackResponse) Reset() {
	*x = RollbackResponse{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackResponse) ProtoMessage() {}

func (x *RollbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackResponse.ProtoReflect.Descriptor instead.
func (*RollbackResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *RollbackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RaftAdminStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminStatusRequest) Reset() {
	*x = RaftAdminStatusRequest{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminStatusRequest) ProtoMessage() {}

func (x *RaftAdminStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminStatusRequest.ProtoReflect.Descriptor instead.
func (*RaftAdminStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

type RaftAdminStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	State             RaftAdminState         `protobuf:"varint,1,opt,name=state,proto3,enum=RaftAdminState" json:"state,omitempty"`
	LeaderId          string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddress     string                 `protobuf:"bytes,3,opt,name=leader_address,json=leaderAddress,proto3" json:"leader_address,omitempty"`
	Term              uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	CommitIndex       uint64                 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	AppliedIndex      uint64                 `protobuf:"varint,6,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	LastLogIndex      uint64                 `protobuf:"varint,7,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastSnapshotIndex uint64                 `protobuf:"varint,8,opt,name=last_snapshot_index,json=lastSnapshotIndex,proto3" json:"last_snapshot_index,omitempty"`
	FsmPending        uint64                 `protobuf:"varint,9,opt,name=fsm_pending,json=fsmPending,proto3" json:"fsm_pending,omitempty"`
	NumPeers          uint64                 `protobuf:"varint,10,opt,name=num_peers,json=numPeers,proto3" json:"num_peers,omitempty"`
	LastContactNanos  int64                  `protobuf:"varint,11,opt,name=last_contact_nanos,json=lastContactNanos,proto3" json:"last_contact_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RaftAdminStatusResponse) Reset() {
	*x = RaftAdminStatusResponse{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminStatusResponse) ProtoMessage() {}

func (x *RaftAdminStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminStatusResponse.ProtoReflect.Descriptor instead.
func (*RaftAdminStatusResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *RaftAdminStatusResponse) GetState() RaftAdminState {
	if x != nil {
		return x.State
	}
	return RaftAdminState_RAFT_ADMIN_STATE_UNKNOWN
}

func (x *RaftAdminStatusResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *RaftAdminStatusResponse) GetLeaderAddress() string {
	if x != nil {
		return x.LeaderAddress
	}
	return ""
}

func (x *RaftAdminStatusResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftAdminStatusResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *RaftAdminStatusResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *RaftAdminStatusResponse) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RaftAdminStatusResponse) GetLastSnapshotIndex() uint64 {
	if x != nil {
		return x.LastSnapshotIndex
	}
	return 0
}

func (x *RaftAdminStatusResponse) GetFsmPending() uint64 {
	if x != nil {
		return x.FsmPending
	}
	return 0
}

func (x *RaftAdminStatusResponse) GetNumPeers() uint64 {
	if x != nil {
		return x.NumPeers
	}
	return 0
}

func (x *RaftAdminStatusResponse) GetLastContactNanos() int64 {
	if x != nil {
		return x.LastContactNanos
	}
	return 0
}

type RaftAdminConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminConfigurationRequest) Reset() {
	*x = RaftAdminConfigurationRequest{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminConfigurationRequest) ProtoMessage() {}

func (x *RaftAdminConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminConfigurationRequest.ProtoReflect.Descriptor instead.
func (*RaftAdminConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

type RaftAdminMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Suffrage      string                 `protobuf:"bytes,3,opt,name=suffrage,proto3" json:"suffrage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminMember) Reset() {
	*x = RaftAdminMember{}
	mi := &file_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminMember) ProtoMessage() {}

func (x *RaftAdminMember) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminMember.ProtoReflect.Descriptor instead.
func (*RaftAdminMember) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{30}
}

func (x *RaftAdminMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftAdminMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RaftAdminMember) GetSuffrage() string {
	if x != nil {
		return x.Suffrage
	}
	return ""
}

type RaftAdminConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*RaftAdminMember     `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminConfigurationResponse) Reset() {
	*x = RaftAdminConfigurationResponse{}
	mi := &file_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminConfigurationResponse) ProtoMessage() {}

func (x *RaftAdminConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminConfigurationResponse.ProtoReflect.Descriptor instead.
func (*RaftAdminConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{31}
}

func (x *RaftAdminConfigurationResponse) GetServers() []*RaftAdminMember {
	if x != nil {
		return x.Servers
	}
	return nil
}

type RaftAdminAddVoterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PreviousIndex uint64                 `protobuf:"varint,3,opt,name=previous_index,json=previousIndex,proto3" json:"previous_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminAddVoterRequest) Reset() {
	*x = RaftAdminAddVoterRequest{}
	mi := &file_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminAddVoterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminAddVoterRequest) ProtoMessage() {}

func (x *RaftAdminAddVoterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminAddVoterRequest.ProtoReflect.Descriptor instead.
func (*RaftAdminAddVoterRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{32}
}

func (x *RaftAdminAddVoterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftAdminAddVoterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RaftAdminAddVoterRequest) GetPreviousIndex() uint64 {
	if x != nil {
		return x.PreviousIndex
	}
	return 0
}

type RaftAdminRemoveServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PreviousIndex uint64                 `protobuf:"varint,2,opt,name=previous_index,json=previousIndex,proto3" json:"previous_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminRemoveServerRequest) Reset() {
	*x = RaftAdminRemoveServerRequest{}
	mi := &file_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminRemoveServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminRemoveServerRequest) ProtoMessage() {}

func (x *RaftAdminRemoveServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminRemoveServerRequest.ProtoReflect.Descriptor instead.
func (*RaftAdminRemoveServerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{33}
}

func (x *RaftAdminRemoveServerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RaftAdminRemoveServerRequest) GetPreviousIndex() uint64 {
	if x != nil {
		return x.PreviousIndex
	}
	return 0
}

type RaftAdminConfigurationChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminConfigurationChangeResponse) Reset() {
	*x = RaftAdminConfigurationChangeResponse{}
	mi := &file_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminConfigurationChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminConfigurationChangeResponse) ProtoMessage() {}

func (x *RaftAdminConfigurationChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminConfigurationChangeResponse.ProtoReflect.Descriptor instead.
func (*RaftAdminConfigurationChangeResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{34}
}

func (x *RaftAdminConfigurationChangeResponse) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RaftAdminTransferLeadershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetAddress string                 `protobuf:"bytes,2,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminTransferLeadershipRequest) Reset() {
	*x = RaftAdminTransferLeadershipRequest{}
	mi := &file_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminTransferLeadershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminTransferLeadershipRequest) ProtoMessage() {}

func (x *RaftAdminTransferLeadershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminTransferLeadershipRequest.ProtoReflect.Descriptor instead.
func (*RaftAdminTransferLeadershipRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{35}
}

func (x *RaftAdminTransferLeadershipRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *RaftAdminTransferLeadershipRequest) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

type RaftAdminTransferLeadershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftAdminTransferLeadershipResponse) Reset() {
	*x = RaftAdminTransferLeadershipResponse{}
	mi := &file_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftAdminTransferLeadershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftAdminTransferLeadershipResponse) ProtoMessage() {}

func (x *RaftAdminTransferLeadershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftAdminTransferLeadershipResponse.ProtoReflect.Descriptor instead.
func (*RaftAdminTransferLeadershipResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{36}
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\"7\n" +
	"\rRawPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"M\n" +
	"\x0eRawPutResponse\x12!\n" +
	"\fcommit_index\x18\x01 \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"1\n" +
	"\rRawGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x04R\x02ts\"b\n" +
	"\x0eRawGetResponse\x12\"\n" +
	"\rread_at_index\x18\x01 \x01(\x04R\vreadAtIndex\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\"$\n" +
	"\x10RawDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"P\n" +
	"\x11RawDeleteResponse\x12!\n" +
	"\fcommit_index\x18\x01 \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\",\n" +
	"\x18RawLatestCommitTSRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"C\n" +
	"\x19RawLatestCommitTSResponse\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x04R\x02ts\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\"\x88\x01\n" +
	"\x10RawScanAtRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x04R\x02ts\x12\x18\n" +
	"\areverse\x18\x05 \x01(\bR\areverse\"3\n" +
	"\tRawKVPair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"/\n" +
	"\x11RawScanAtResponse\x12\x1a\n" +
	"\x02kv\x18\x01 \x03(\v2\n" +
	".RawKVPairR\x02kv\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"J\n" +
	"\vPutResponse\x12!\n" +
	"\fcommit_index\x18\x01 \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"M\n" +
	"\x0eDeleteResponse\x12!\n" +
	"\fcommit_index\x18\x01 \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"G\n" +
	"\vGetResponse\x12\"\n" +
	"\rread_at_index\x18\x01 \x01(\x04R\vreadAtIndex\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"B\n" +
	"\bKeyError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\"M\n" +
	"\x02Kv\x12\x1f\n" +
	"\x05error\x18\x01 \x01(\v2\t.KeyErrorR\x05error\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"Y\n" +
	"\vScanRequest\x12\x1b\n" +
	"\tstart_key\x18\x01 \x01(\fR\bstartKey\x12\x17\n" +
	"\aend_key\x18\x02 \x01(\fR\x06endKey\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\"#\n" +
	"\fScanResponse\x12\x13\n" +
	"\x02kv\x18\x01 \x03(\v2\x03.KvR\x02kv\"j\n" +
	"\x0fPreWriteRequest\x12!\n" +
	"\tmutations\x18\x02 \x03(\v2\x03.KvR\tmutations\x12\x19\n" +
	"\bstart_ts\x18\x03 \x01(\x04R\astartTs\x12\x19\n" +
	"\block_ttl\x18\x04 \x01(\x04R\alockTtl\"6\n" +
	"\x11PreCommitResponse\x12!\n" +
	"\x06errors\x18\x01 \x03(\v2\t.KeyErrorR\x06errors\">\n" +
	"\rCommitRequest\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\x12\x12\n" +
	"\x04keys\x18\x02 \x03(\fR\x04keys\"p\n" +
	"\x0eCommitResponse\x12!\n" +
	"\fcommit_index\x18\x01 \x01(\x04R\vcommitIndex\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\x06errors\x18\x03 \x03(\v2\t.KeyErrorR\x06errors\",\n" +
	"\x0fRollbackRequest\x12\x19\n" +
	"\bstart_ts\x18\x01 \x01(\x04R\astartTs\",\n" +
	"\x10RollbackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x18\n" +
	"\x16RaftAdminStatusRequest\"\xa2\x03\n" +
	"\x17RaftAdminStatusResponse\x12%\n" +
	"\x05state\x18\x01 \x01(\x0e2\x0f.RaftAdminStateR\x05state\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12%\n" +
	"\x0eleader_address\x18\x03 \x01(\tR\rleaderAddress\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndex\x12#\n" +
	"\rapplied_index\x18\x06 \x01(\x04R\fappliedIndex\x12$\n" +
	"\x0elast_log_index\x18\a \x01(\x04R\flastLogIndex\x12.\n" +
	"\x13last_snapshot_index\x18\b \x01(\x04R\x11lastSnapshotIndex\x12\x1f\n" +
	"\vfsm_pending\x18\t \x01(\x04R\n" +
	"fsmPending\x12\x1b\n" +
	"\tnum_peers\x18\n" +
	" \x01(\x04R\bnumPeers\x12,\n" +
	"\x12last_contact_nanos\x18\v \x01(\x03R\x10lastContactNanos\"\x1f\n" +
	"\x1dRaftAdminConfigurationRequest\"W\n" +
	"\x0fRaftAdminMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bsuffrage\x18\x03 \x01(\tR\bsuffrage\"L\n" +
	"\x1eRaftAdminConfigurationResponse\x12*\n" +
	"\aservers\x18\x01 \x03(\v2\x10.RaftAdminMemberR\aservers\"k\n" +
	"\x18RaftAdminAddVoterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12%\n" +
	"\x0eprevious_index\x18\x03 \x01(\x04R\rpreviousIndex\"U\n" +
	"\x1cRaftAdminRemoveServerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eprevious_index\x18\x02 \x01(\x04R\rpreviousIndex\"<\n" +
	"$RaftAdminConfigurationChangeResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\"h\n" +
	"\"RaftAdminTransferLeadershipRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12%\n" +
	"\x0etarget_address\x18\x02 \x01(\tR\rtargetAddress\"%\n" +
	"#RaftAdminTransferLeadershipResponse*\xa9\x01\n" +
	"\x0eRaftAdminState\x12\x1c\n" +
	"\x18RAFT_ADMIN_STATE_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19RAFT_ADMIN_STATE_FOLLOWER\x10\x01\x12\x1e\n" +
	"\x1aRAFT_ADMIN_STATE_CANDIDATE\x10\x02\x12\x1b\n" +
	"\x17RAFT_ADMIN_STATE_LEADER\x10\x03\x12\x1d\n" +
	"\x19RAFT_ADMIN_STATE_SHUTDOWN\x10\x042\x9b\x02\n" +
	"\x05RawKV\x12+\n" +
	"\x06RawPut\x12\x0e.RawPutRequest\x1a\x0f.RawPutResponse\"\x00\x12+\n" +
	"\x06RawGet\x12\x0e.RawGetRequest\x1a\x0f.RawGetResponse\"\x00\x124\n" +
	"\tRawDelete\x12\x11.RawDeleteRequest\x1a\x12.RawDeleteResponse\"\x00\x12L\n" +
	"\x11RawLatestCommitTS\x12\x19.RawLatestCommitTSRequest\x1a\x1a.RawLatestCommitTSResponse\"\x00\x124\n" +
	"\tRawScanAt\x12\x11.RawScanAtRequest\x1a\x12.RawScanAtResponse\"\x002\xc1\x02\n" +
	"\x0fTransactionalKV\x12\"\n" +
	"\x03Put\x12\v.PutRequest\x1a\f.PutResponse\"\x00\x12\"\n" +
	"\x03Get\x12\v.GetRequest\x1a\f.GetResponse\"\x00\x12+\n" +
	"\x06Delete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\"\x00\x12%\n" +
	"\x04Scan\x12\f.ScanRequest\x1a\r.ScanResponse\"\x00\x122\n" +
	"\bPreWrite\x12\x10.PreWriteRequest\x1a\x12.PreCommitResponse\"\x00\x12+\n" +
	"\x06Commit\x12\x0e.CommitRequest\x1a\x0f.CommitResponse\"\x00\x121\n" +
	"\bRollback\x12\x10.RollbackRequest\x1a\x11.RollbackResponse\"\x002\xa9\x03\n" +
	"\tRaftAdmin\x12=\n" +
	"\x06Status\x12\x17.RaftAdminStatusRequest\x1a\x18.RaftAdminStatusResponse\"\x00\x12R\n" +
	"\rConfiguration\x12\x1e.RaftAdminConfigurationRequest\x1a\x1f.RaftAdminConfigurationResponse\"\x00\x12N\n" +
	"\bAddVoter\x12\x19.RaftAdminAddVoterRequest\x1a%.RaftAdminConfigurationChangeResponse\"\x00\x12V\n" +
	"\fRemoveServer\x12\x1d.RaftAdminRemoveServerRequest\x1a%.RaftAdminConfigurationChangeResponse\"\x00\x12a\n" +
	"\x12TransferLeadership\x12#.RaftAdminTransferLeadershipRequest\x1a$.RaftAdminTransferLeadershipResponse\"\x00B#Z!github.com/bootjp/elastickv/protob\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_service_proto_goTypes = []any{
	(RaftAdminState)(0),                          // 0: RaftAdminState
	(*RawPutRequest)(nil),                        // 1: RawPutRequest
	(*RawPutResponse)(nil),                       // 2: RawPutResponse
	(*RawGetRequest)(nil),                        // 3: RawGetRequest
	(*RawGetResponse)(nil),                       // 4: RawGetResponse
	(*RawDeleteRequest)(nil),                     // 5: RawDeleteRequest
	(*RawDeleteResponse)(nil),                    // 6: RawDeleteResponse
	(*RawLatestCommitTSRequest)(nil),             // 7: RawLatestCommitTSRequest
	(*RawLatestCommitTSResponse)(nil),            // 8: RawLatestCommitTSResponse
	(*RawScanAtRequest)(nil),                     // 9: RawScanAtRequest
	(*RawKVPair)(nil),                            // 10: RawKVPair
	(*RawScanAtResponse)(nil),                    // 11: RawScanAtResponse
	(*PutRequest)(nil),                           // 12: PutRequest
	(*PutResponse)(nil),                          // 13: PutResponse
	(*DeleteRequest)(nil),                        // 14: DeleteRequest
	(*DeleteResponse)(nil),                       // 15: DeleteResponse
	(*GetRequest)(nil),                           // 16: GetRequest
	(*GetResponse)(nil),                          // 17: GetResponse
	(*KeyError)(nil),                             // 18: KeyError
	(*Kv)(nil),                                   // 19: Kv
	(*ScanRequest)(nil),                          // 20: ScanRequest
	(*ScanResponse)(nil),                         // 21: ScanResponse
	(*PreWriteRequest)(nil),                      // 22: PreWriteRequest
	(*PreCommitResponse)(nil),                    // 23: PreCommitResponse
	(*CommitRequest)(nil),                        // 24: CommitRequest
	(*CommitResponse)(nil),                       // 25: CommitResponse
	(*RollbackRequest)(nil),                      // 26: RollbackRequest
	(*RollbackResponse)(nil),                     // 27: RollbackResponse
	(*RaftAdminStatusRequest)(nil),               // 28: RaftAdminStatusRequest
	(*RaftAdminStatusResponse)(nil),              // 29: RaftAdminStatusResponse
	(*RaftAdminConfigurationRequest)(nil),        // 30: RaftAdminConfigurationRequest
	(*RaftAdminMember)(nil),                      // 31: RaftAdminMember
	(*RaftAdminConfigurationResponse)(nil),       // 32: RaftAdminConfigurationResponse
	(*RaftAdminAddVoterRequest)(nil),             // 33: RaftAdminAddVoterRequest
	(*RaftAdminRemoveServerRequest)(nil),         // 34: RaftAdminRemoveServerRequest
	(*RaftAdminConfigurationChangeResponse)(nil), // 35: RaftAdminConfigurationChangeResponse
	(*RaftAdminTransferLeadershipRequest)(nil),   // 36: RaftAdminTransferLeadershipRequest
	(*RaftAdminTransferLeadershipResponse)(nil),  // 37: RaftAdminTransferLeadershipResponse
}
var file_service_proto_depIdxs = []int32{
	10, // 0: RawScanAtResponse.kv:type_name -> RawKVPair
	18, // 1: Kv.error:type_name -> KeyError
	19, // 2: ScanResponse.kv:type_name -> Kv
	19, // 3: PreWriteRequest.mutations:type_name -> Kv
	18, // 4: PreCommitResponse.errors:type_name -> KeyError
	18, // 5: CommitResponse.errors:type_name -> KeyError
	0,  // 6: RaftAdminStatusResponse.state:type_name -> RaftAdminState
	31, // 7: RaftAdminConfigurationResponse.servers:type_name -> RaftAdminMember
	1,  // 8: RawKV.RawPut:input_type -> RawPutRequest
	3,  // 9: RawKV.RawGet:input_type -> RawGetRequest
	5,  // 10: RawKV.RawDelete:input_type -> RawDeleteRequest
	7,  // 11: RawKV.RawLatestCommitTS:input_type -> RawLatestCommitTSRequest
	9,  // 12: RawKV.RawScanAt:input_type -> RawScanAtRequest
	12, // 13: TransactionalKV.Put:input_type -> PutRequest
	16, // 14: TransactionalKV.Get:input_type -> GetRequest
	14, // 15: TransactionalKV.Delete:input_type -> DeleteRequest
	20, // 16: TransactionalKV.Scan:input_type -> ScanRequest
	22, // 17: TransactionalKV.PreWrite:input_type -> PreWriteRequest
	24, // 18: TransactionalKV.Commit:input_type -> CommitRequest
	26, // 19: TransactionalKV.Rollback:input_type -> RollbackRequest
	28, // 20: RaftAdmin.Status:input_type -> RaftAdminStatusRequest
	30, // 21: RaftAdmin.Configuration:input_type -> RaftAdminConfigurationRequest
	33, // 22: RaftAdmin.AddVoter:input_type -> RaftAdminAddVoterRequest
	34, // 23: RaftAdmin.RemoveServer:input_type -> RaftAdminRemoveServerRequest
	36, // 24: RaftAdmin.TransferLeadership:input_type -> RaftAdminTransferLeadershipRequest
	2,  // 25: RawKV.RawPut:output_type -> RawPutResponse
	4,  // 26: RawKV.RawGet:output_type -> RawGetResponse
	6,  // 27: RawKV.RawDelete:output_type -> RawDeleteResponse
	8,  // 28: RawKV.RawLatestCommitTS:output_type -> RawLatestCommitTSResponse
	11, // 29: RawKV.RawScanAt:output_type -> RawScanAtResponse
	13, // 30: TransactionalKV.Put:output_type -> PutResponse
	17, // 31: TransactionalKV.Get:output_type -> GetResponse
	15, // 32: TransactionalKV.Delete:output_type -> DeleteResponse
	21, // 33: TransactionalKV.Scan:output_type -> ScanResponse
	23, // 34: TransactionalKV.PreWrite:output_type -> PreCommitResponse
	25, // 35: TransactionalKV.Commit:output_type -> CommitResponse
	27, // 36: TransactionalKV.Rollback:output_type -> RollbackResponse
	29, // 37: RaftAdmin.Status:output_type -> RaftAdminStatusResponse
	32, // 38: RaftAdmin.Configuration:output_type -> RaftAdminConfigurationResponse
	35, // 39: RaftAdmin.AddVoter:output_type -> RaftAdminConfigurationChangeResponse
	35, // 40: RaftAdmin.RemoveServer:output_type -> RaftAdminConfigurationChangeResponse
	37, // 41: RaftAdmin.TransferLeadership:output_type -> RaftAdminTransferLeadershipResponse
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
