//go:cgo_ldflag "-O2"
//go:cgo_ldflag "-g"
// Code generated by cmd/cgo; DO NOT EDIT.

package zstd

import "unsafe"

import "syscall"

import _cgopackage "runtime/cgo"

type _ _cgopackage.Incomplete
var _ syscall.Errno
func _Cgo_ptr(ptr unsafe.Pointer) unsafe.Pointer { return ptr }

//go:linkname _Cgo_always_false runtime.cgoAlwaysFalse
var _Cgo_always_false bool
//go:linkname _Cgo_use runtime.cgoUse
func _Cgo_use(interface{})
//go:linkname _Cgo_keepalive runtime.cgoKeepAlive
//go:noescape
func _Cgo_keepalive(interface{})
//go:linkname _Cgo_no_callback runtime.cgoNoCallback
func _Cgo_no_callback(bool)
type _Ctype_ZSTD_CCtx = _Ctype_struct_ZSTD_CCtx_s

type _Ctype_ZSTD_CDict = _Ctype_struct_ZSTD_CDict_s

type _Ctype_ZSTD_CStream = _Ctype_struct_ZSTD_CCtx_s

type _Ctype_ZSTD_DCtx = _Ctype_struct_ZSTD_DCtx_s

type _Ctype_ZSTD_DDict = _Ctype_struct_ZSTD_DDict_s

type _Ctype_ZSTD_DStream = _Ctype_struct_ZSTD_DCtx_s

type _Ctype_ZSTD_ResetDirective uint32

type _Ctype_ZSTD_cParameter uint32

type _Ctype__GoString_ string

type _Ctype_char int8

type _Ctype_compressStream2_result = _Ctype_struct_compressStream2_result_s

type _Ctype_decompressStream2_result = _Ctype_struct_decompressStream2_result_s

type _Ctype_int int32

type _Ctype_intgo = _Ctype_ptrdiff_t

type _Ctype_long int64

type _Ctype_ptrdiff_t = _Ctype_long

type _Ctype_size_t = _Ctype_ulong

type _Ctype_struct_ZSTD_CCtx_s _cgopackage.Incomplete

type _Ctype_struct_ZSTD_CDict_s _cgopackage.Incomplete

type _Ctype_struct_ZSTD_DCtx_s _cgopackage.Incomplete

type _Ctype_struct_ZSTD_DDict_s _cgopackage.Incomplete

type _Ctype_struct_compressStream2_result_s struct {
	return_code	_Ctype_size_t
	bytes_consumed	_Ctype_size_t
	bytes_written	_Ctype_size_t
}

type _Ctype_struct_decompressStream2_result_s struct {
	return_code	_Ctype_size_t
	bytes_consumed	_Ctype_size_t
	bytes_written	_Ctype_size_t
}

type _Ctype_uint uint32

type _Ctype_ulong uint64

type _Ctype_ulonglong uint64

type _Ctype_void [0]byte

//go:linkname _cgo_runtime_cgocall runtime.cgocall
func _cgo_runtime_cgocall(unsafe.Pointer, uintptr) int32

//go:linkname _cgoCheckPointer runtime.cgoCheckPointer
//go:noescape
func _cgoCheckPointer(interface{}, interface{})

//go:linkname _cgoCheckResult runtime.cgoCheckResult
//go:noescape
func _cgoCheckResult(interface{})
const _Ciconst_ZSTD_c_compressionLevel = 0x64
const _Ciconst_ZSTD_c_nbWorkers = 0x190
const _Ciconst_ZSTD_reset_session_only = 0x1


//go:linkname _cgo_runtime_gostring runtime.gostring
func _cgo_runtime_gostring(*_Ctype_char) string

// GoString converts the C string p into a Go string.
func _Cfunc_GoString(p *_Ctype_char) string {
	return _cgo_runtime_gostring(p)
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_CCtx_loadDictionary
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_CCtx_loadDictionary _cgo_833553befd65_Cfunc_ZSTD_CCtx_loadDictionary
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_CCtx_loadDictionary byte
var _cgo_833553befd65_Cfunc_ZSTD_CCtx_loadDictionary = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_CCtx_loadDictionary)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_CCtx_loadDictionary(p0 *_Ctype_struct_ZSTD_CCtx_s, p1 unsafe.Pointer, p2 _Ctype_size_t) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_CCtx_loadDictionary, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_CCtx_setParameter
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_CCtx_setParameter _cgo_833553befd65_Cfunc_ZSTD_CCtx_setParameter
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_CCtx_setParameter byte
var _cgo_833553befd65_Cfunc_ZSTD_CCtx_setParameter = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_CCtx_setParameter)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_CCtx_setParameter(p0 *_Ctype_struct_ZSTD_CCtx_s, p1 _Ctype_ZSTD_cParameter, p2 _Ctype_int) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_CCtx_setParameter, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_DCtx_loadDictionary
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_DCtx_loadDictionary _cgo_833553befd65_Cfunc_ZSTD_DCtx_loadDictionary
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_DCtx_loadDictionary byte
var _cgo_833553befd65_Cfunc_ZSTD_DCtx_loadDictionary = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_DCtx_loadDictionary)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_DCtx_loadDictionary(p0 *_Ctype_struct_ZSTD_DCtx_s, p1 unsafe.Pointer, p2 _Ctype_size_t) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_DCtx_loadDictionary, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_DCtx_reset
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_DCtx_reset _cgo_833553befd65_Cfunc_ZSTD_DCtx_reset
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_DCtx_reset byte
var _cgo_833553befd65_Cfunc_ZSTD_DCtx_reset = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_DCtx_reset)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_DCtx_reset(p0 *_Ctype_struct_ZSTD_DCtx_s, p1 _Ctype_ZSTD_ResetDirective) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_DCtx_reset, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_DStreamInSize
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_DStreamInSize _cgo_833553befd65_Cfunc_ZSTD_DStreamInSize
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_DStreamInSize byte
var _cgo_833553befd65_Cfunc_ZSTD_DStreamInSize = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_DStreamInSize)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_DStreamInSize() (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_DStreamInSize, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_DStreamOutSize
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_DStreamOutSize _cgo_833553befd65_Cfunc_ZSTD_DStreamOutSize
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_DStreamOutSize byte
var _cgo_833553befd65_Cfunc_ZSTD_DStreamOutSize = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_DStreamOutSize)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_DStreamOutSize() (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_DStreamOutSize, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_compress
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_compress _cgo_833553befd65_Cfunc_ZSTD_compress
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_compress byte
var _cgo_833553befd65_Cfunc_ZSTD_compress = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_compress)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_compress(p0 unsafe.Pointer, p1 _Ctype_size_t, p2 unsafe.Pointer, p3 _Ctype_size_t, p4 _Ctype_int) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_compress, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_compressBound
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressBound _cgo_833553befd65_Cfunc_ZSTD_compressBound
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressBound byte
var _cgo_833553befd65_Cfunc_ZSTD_compressBound = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_compressBound)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_compressBound(p0 _Ctype_size_t) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_compressBound, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_compressCCtx
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressCCtx _cgo_833553befd65_Cfunc_ZSTD_compressCCtx
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressCCtx byte
var _cgo_833553befd65_Cfunc_ZSTD_compressCCtx = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_compressCCtx)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_compressCCtx(p0 *_Ctype_struct_ZSTD_CCtx_s, p1 unsafe.Pointer, p2 _Ctype_size_t, p3 unsafe.Pointer, p4 _Ctype_size_t, p5 _Ctype_int) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_compressCCtx, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
		_Cgo_use(p5)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_compressStream2_finish
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_finish _cgo_833553befd65_Cfunc_ZSTD_compressStream2_finish
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_finish byte
var _cgo_833553befd65_Cfunc_ZSTD_compressStream2_finish = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_finish)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_compressStream2_finish(p0 *_Ctype_struct_compressStream2_result_s, p1 *_Ctype_struct_ZSTD_CCtx_s, p2 unsafe.Pointer, p3 _Ctype_size_t, p4 unsafe.Pointer, p5 _Ctype_size_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_compressStream2_finish, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
		_Cgo_use(p5)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_compressStream2_flush
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_flush _cgo_833553befd65_Cfunc_ZSTD_compressStream2_flush
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_flush byte
var _cgo_833553befd65_Cfunc_ZSTD_compressStream2_flush = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_flush)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_compressStream2_flush(p0 *_Ctype_struct_compressStream2_result_s, p1 *_Ctype_struct_ZSTD_CCtx_s, p2 unsafe.Pointer, p3 _Ctype_size_t, p4 unsafe.Pointer, p5 _Ctype_size_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_compressStream2_flush, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
		_Cgo_use(p5)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_compressStream2_wrapper
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_wrapper _cgo_833553befd65_Cfunc_ZSTD_compressStream2_wrapper
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_wrapper byte
var _cgo_833553befd65_Cfunc_ZSTD_compressStream2_wrapper = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_compressStream2_wrapper)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_compressStream2_wrapper(p0 *_Ctype_struct_compressStream2_result_s, p1 *_Ctype_struct_ZSTD_CCtx_s, p2 unsafe.Pointer, p3 _Ctype_size_t, p4 unsafe.Pointer, p5 _Ctype_size_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_compressStream2_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
		_Cgo_use(p5)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_compress_usingCDict
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_compress_usingCDict _cgo_833553befd65_Cfunc_ZSTD_compress_usingCDict
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_compress_usingCDict byte
var _cgo_833553befd65_Cfunc_ZSTD_compress_usingCDict = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_compress_usingCDict)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_compress_usingCDict(p0 *_Ctype_struct_ZSTD_CCtx_s, p1 unsafe.Pointer, p2 _Ctype_size_t, p3 unsafe.Pointer, p4 _Ctype_size_t, p5 *_Ctype_struct_ZSTD_CDict_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_compress_usingCDict, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
		_Cgo_use(p5)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_createCCtx
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_createCCtx _cgo_833553befd65_Cfunc_ZSTD_createCCtx
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_createCCtx byte
var _cgo_833553befd65_Cfunc_ZSTD_createCCtx = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_createCCtx)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_createCCtx() (r1 *_Ctype_struct_ZSTD_CCtx_s) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_createCCtx, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_createCDict
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_createCDict _cgo_833553befd65_Cfunc_ZSTD_createCDict
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_createCDict byte
var _cgo_833553befd65_Cfunc_ZSTD_createCDict = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_createCDict)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_createCDict(p0 unsafe.Pointer, p1 _Ctype_size_t, p2 _Ctype_int) (r1 *_Ctype_struct_ZSTD_CDict_s) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_createCDict, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_createCStream
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_createCStream _cgo_833553befd65_Cfunc_ZSTD_createCStream
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_createCStream byte
var _cgo_833553befd65_Cfunc_ZSTD_createCStream = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_createCStream)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_createCStream() (r1 *_Ctype_struct_ZSTD_CCtx_s) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_createCStream, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_createDCtx
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_createDCtx _cgo_833553befd65_Cfunc_ZSTD_createDCtx
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_createDCtx byte
var _cgo_833553befd65_Cfunc_ZSTD_createDCtx = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_createDCtx)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_createDCtx() (r1 *_Ctype_struct_ZSTD_DCtx_s) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_createDCtx, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_createDDict
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_createDDict _cgo_833553befd65_Cfunc_ZSTD_createDDict
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_createDDict byte
var _cgo_833553befd65_Cfunc_ZSTD_createDDict = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_createDDict)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_createDDict(p0 unsafe.Pointer, p1 _Ctype_size_t) (r1 *_Ctype_struct_ZSTD_DDict_s) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_createDDict, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_createDStream
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_createDStream _cgo_833553befd65_Cfunc_ZSTD_createDStream
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_createDStream byte
var _cgo_833553befd65_Cfunc_ZSTD_createDStream = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_createDStream)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_createDStream() (r1 *_Ctype_struct_ZSTD_DCtx_s) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_createDStream, uintptr(unsafe.Pointer(&r1)))
	if _Cgo_always_false {
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_decompress
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompress _cgo_833553befd65_Cfunc_ZSTD_decompress
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompress byte
var _cgo_833553befd65_Cfunc_ZSTD_decompress = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_decompress)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_decompress(p0 unsafe.Pointer, p1 _Ctype_size_t, p2 unsafe.Pointer, p3 _Ctype_size_t) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_decompress, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_decompressDCtx
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompressDCtx _cgo_833553befd65_Cfunc_ZSTD_decompressDCtx
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompressDCtx byte
var _cgo_833553befd65_Cfunc_ZSTD_decompressDCtx = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_decompressDCtx)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_decompressDCtx(p0 *_Ctype_struct_ZSTD_DCtx_s, p1 unsafe.Pointer, p2 _Ctype_size_t, p3 unsafe.Pointer, p4 _Ctype_size_t) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_decompressDCtx, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_decompressStream_wrapper
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompressStream_wrapper _cgo_833553befd65_Cfunc_ZSTD_decompressStream_wrapper
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompressStream_wrapper byte
var _cgo_833553befd65_Cfunc_ZSTD_decompressStream_wrapper = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_decompressStream_wrapper)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_decompressStream_wrapper(p0 *_Ctype_struct_decompressStream2_result_s, p1 *_Ctype_struct_ZSTD_DCtx_s, p2 unsafe.Pointer, p3 _Ctype_size_t, p4 unsafe.Pointer, p5 _Ctype_size_t) (r1 _Ctype_void) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_decompressStream_wrapper, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
		_Cgo_use(p5)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_decompress_usingDDict
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompress_usingDDict _cgo_833553befd65_Cfunc_ZSTD_decompress_usingDDict
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_decompress_usingDDict byte
var _cgo_833553befd65_Cfunc_ZSTD_decompress_usingDDict = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_decompress_usingDDict)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_decompress_usingDDict(p0 *_Ctype_struct_ZSTD_DCtx_s, p1 unsafe.Pointer, p2 _Ctype_size_t, p3 unsafe.Pointer, p4 _Ctype_size_t, p5 *_Ctype_struct_ZSTD_DDict_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_decompress_usingDDict, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
		_Cgo_use(p2)
		_Cgo_use(p3)
		_Cgo_use(p4)
		_Cgo_use(p5)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_freeCCtx
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCCtx _cgo_833553befd65_Cfunc_ZSTD_freeCCtx
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCCtx byte
var _cgo_833553befd65_Cfunc_ZSTD_freeCCtx = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCCtx)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_freeCCtx(p0 *_Ctype_struct_ZSTD_CCtx_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_freeCCtx, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_freeCDict
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCDict _cgo_833553befd65_Cfunc_ZSTD_freeCDict
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCDict byte
var _cgo_833553befd65_Cfunc_ZSTD_freeCDict = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCDict)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_freeCDict(p0 *_Ctype_struct_ZSTD_CDict_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_freeCDict, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_freeCStream
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCStream _cgo_833553befd65_Cfunc_ZSTD_freeCStream
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCStream byte
var _cgo_833553befd65_Cfunc_ZSTD_freeCStream = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_freeCStream)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_freeCStream(p0 *_Ctype_struct_ZSTD_CCtx_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_freeCStream, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_freeDCtx
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDCtx _cgo_833553befd65_Cfunc_ZSTD_freeDCtx
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDCtx byte
var _cgo_833553befd65_Cfunc_ZSTD_freeDCtx = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDCtx)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_freeDCtx(p0 *_Ctype_struct_ZSTD_DCtx_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_freeDCtx, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_freeDDict
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDDict _cgo_833553befd65_Cfunc_ZSTD_freeDDict
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDDict byte
var _cgo_833553befd65_Cfunc_ZSTD_freeDDict = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDDict)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_freeDDict(p0 *_Ctype_struct_ZSTD_DDict_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_freeDDict, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_freeDStream
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDStream _cgo_833553befd65_Cfunc_ZSTD_freeDStream
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDStream byte
var _cgo_833553befd65_Cfunc_ZSTD_freeDStream = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_freeDStream)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_freeDStream(p0 *_Ctype_struct_ZSTD_DCtx_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_freeDStream, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_getErrorName
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_getErrorName _cgo_833553befd65_Cfunc_ZSTD_getErrorName
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_getErrorName byte
var _cgo_833553befd65_Cfunc_ZSTD_getErrorName = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_getErrorName)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_getErrorName(p0 _Ctype_size_t) (r1 *_Ctype_char) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_getErrorName, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_getFrameContentSize
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_getFrameContentSize _cgo_833553befd65_Cfunc_ZSTD_getFrameContentSize
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_getFrameContentSize byte
var _cgo_833553befd65_Cfunc_ZSTD_getFrameContentSize = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_getFrameContentSize)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_getFrameContentSize(p0 unsafe.Pointer, p1 _Ctype_size_t) (r1 _Ctype_ulonglong) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_getFrameContentSize, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
		_Cgo_use(p1)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_initDStream
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_initDStream _cgo_833553befd65_Cfunc_ZSTD_initDStream
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_initDStream byte
var _cgo_833553befd65_Cfunc_ZSTD_initDStream = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_initDStream)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_initDStream(p0 *_Ctype_struct_ZSTD_DCtx_s) (r1 _Ctype_size_t) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_initDStream, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
//go:cgo_import_static _cgo_833553befd65_Cfunc_ZSTD_isError
//go:linkname __cgofn__cgo_833553befd65_Cfunc_ZSTD_isError _cgo_833553befd65_Cfunc_ZSTD_isError
var __cgofn__cgo_833553befd65_Cfunc_ZSTD_isError byte
var _cgo_833553befd65_Cfunc_ZSTD_isError = unsafe.Pointer(&__cgofn__cgo_833553befd65_Cfunc_ZSTD_isError)

//go:cgo_unsafe_args
func _Cfunc_ZSTD_isError(p0 _Ctype_size_t) (r1 _Ctype_uint) {
	_cgo_runtime_cgocall(_cgo_833553befd65_Cfunc_ZSTD_isError, uintptr(unsafe.Pointer(&p0)))
	if _Cgo_always_false {
		_Cgo_use(p0)
	}
	return
}
