name: Reviewdog

on:
  pull_request:
    types: [ opened, synchronize ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-reviewdog
#  cancel-in-progress: true

jobs:
  golangci-lint:
    name: golangci-lint
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.x"
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$(go env GOPATH)/bin" v2.9.0
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Run golangci-lint
        run: golangci-lint run --config=.golangci.yaml
      - name: golangci-lint
        continue-on-error: true
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_version: "v2.9.0"
          level: warning
          golangci_lint_flags: "--config=.golangci.yaml"
          filter_mode: nofilter
          reporter: github-pr-review
          cache: false
          fail_on_error: false
